Repository codeit-bootcamp-frontend/5-Weekly-Mission, pull requests merged in 2024-05, with the labels that each got.

#366 [박상준] Week11
  public/5-Weekly-Mission.code-workspace
  src/App.css
  src/App.jsx
  src/api/api.js
  src/assets/Facebook.svg
  src/assets/Kakao.svg
  src/assets/add.svg
  src/assets/addPurple.svg
  src/assets/check.svg
  src/assets/close.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.styled.js
  src/components/ContentsContainer.jsx
  src/components/FolderButton/FolderButton.jsx
  src/components/FolderButton/FolderButton.styled.js
  src/components/FolderButtonContainer/FolderButtonContainer.jsx
  src/components/FolderButtonContainer/FolderButtonContainer.styled.js
  src/components/Footer/Footer.styled.js
  src/components/KebabMenu/KebabMenu.jsx
  src/components/KebabMenu/KebabMenu.styled.js
  src/components/Layout.jsx
  src/components/Modal/AddFolderModal/AddFolderModal.jsx
  src/components/Modal/AddModal/AddModal.jsx
  src/components/Modal/AddModal/AddModal.styled.js
  src/components/Modal/DeleteLinkModal/DeleteLinkModal.jsx
  src/components/Modal/DeleteModal/DeleteModal.jsx
  src/components/Modal/DeleteModal/DeleteModal.styled.js
  src/components/Modal/EditModal/EditModal.jsx
  src/components/Modal/EditModal/EditModal.styled.js
  src/components/Modal/Modals/Modals.jsx
  src/components/Modal/Modals/Modals.styled.js
  src/components/Modal/ShareModal/ShareModal.jsx
  src/components/Modal/ShareModal/ShareModal.styled.js
  src/components/SearchBar/SearchBar.styled.js
  src/hooks/useGetFolder.js
  src/hooks/useGetFolderList.js
  src/hooks/useGetUser.js
  src/pages/Folder/Folder.jsx
  src/pages/Folder/Folder.styled.js
  src/pages/Main/Main.jsx
  src/pages/Shared/Shared.jsx
  src/pages/Shared/Shared.styled..js
Labels: 매운맛🔥, 미완성🫠

#354 [전유민] Week11
  public/images/icon/check.svg
  public/images/icon/modalClose.svg
  src/components/ Modals/AddFolderModal.jsx
  src/components/ Modals/AddLinkModal.jsx
  src/components/ Modals/DeleteModal.jsx
  src/components/ Modals/Modals.style.js
  src/components/AddLink/AddLink.jsx
  src/components/Folder/FolderToolBar.jsx
  src/components/Folder/constant.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.js
  src/components/Modal/ModalContentBox.jsx
  src/components/Modal/ModalContentBox.style.js
  src/components/Modal/ModalFolderItem.jsx
  src/components/Modal/ModalFolderItem.style.js
  src/components/Modal/constant.js
  src/components/Portal.jsx
  src/pages/FolderPage.jsx
  src/styles/button.css
  src/styles/color.css
  src/styles/common.css
Labels: 미완성🫠

#329 [우제윤 ] Week8
  package-lock.json
  package.json
  public/assets/Ellipse 19.png
  public/assets/Group19.png
  public/assets/kebab.png
  public/assets/link.png
  src/App.js
  src/CardList/CardList.css
  src/NavigationBar/NavigationBar.css
  src/NavigationBar/NavigationBar.js
  src/SearchBar/SearchBar.css
  src/SearchBar/SearchBar.js
  src/api/getUserFolder.js
  src/api/useFolderAsync.js
  src/colors.css
  src/common.css
  src/components/FolderCardList.js
  src/components/FolderCardListItem.js
  src/components/FolderCardListItemStyled.js
  src/components/FolderList.css
  src/components/FolderList.js
  src/components/FolderListMenu.js
  src/components/InputAddLink.css
  src/components/InputAddLink.js
  src/components/KebabButton.js
  src/components/LinkIcon.js
  src/components/LinkList.js
  src/components/Test.js
  src/components/Testt.js
  src/components/modal/DeleteModal.js
  src/components/modal/DeleteModalStyled.js
  src/global.css
  src/page/Folder.js
  src/page/Folder.module.css
  src/page/Shared.js
Labels: 순한맛🐑

#352 [홍진호] week11
  .gitignore
  bun.lockb
  package-lock.json
  package.json
  public/facebook1.png
  public/kakao1.png
  public/link1.png
  src/App.tsx
  src/assets/react.svg
  src/components/card-wrapper.tsx
  src/components/feed-wrapper.tsx
  src/components/hero-warpper.tsx
  src/components/logo.tsx
  src/components/navbar.tsx
  src/components/provider/swr-provider.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/skeleton.tsx
  src/components/user-icon.tsx
  src/components/user-name.tsx
  src/data/folders.ts
  src/data/users.ts
  src/index.css
  src/lib/api.ts
  src/lib/date.ts
  src/lib/utils.ts
  src/main.tsx
  src/pages/error/page.tsx
  src/pages/folder/_components/action-button-group.tsx
  src/pages/folder/_components/actionable-dropdown-menu.tsx
  src/pages/folder/_components/add-folder-button.tsx
  src/pages/folder/_components/category-buttons.tsx
  src/pages/folder/_components/control-buttons.tsx
  src/pages/folder/_components/folder-card.tsx
  src/pages/folder/_components/folder-cards.tsx
  src/pages/folder/_components/hero.tsx
  src/pages/folder/_components/link-category-button.tsx
  src/pages/folder/_components/link-search-bar.tsx
  src/pages/folder/page.tsx
  src/pages/home/page.tsx
  src/pages/link-detail/page.tsx
  src/pages/shared/_components/hero.tsx
  src/pages/shared/_components/link-card-list.tsx
  src/pages/shared/_components/link-card.tsx
  src/pages/shared/_components/link-cards.tsx
  src/pages/shared/_components/user-account-nav.tsx
  src/pages/shared/page.tsx
  src/services/fetcher.ts
  src/services/queries.ts
  src/types/index.ts
  tsconfig.json
Labels: 순한맛🐑

#368 [김보민] week11
  .DS_Store
  package-lock.json
  package.json
  public/images/Group 36.svg
  public/images/_close.png
  public/images/add.svg
  public/images/kebab.svg
  public/images/pen.svg
  public/images/share.svg
  src/components/ErrorComponent/ErrorComponent.css
  src/components/ErrorComponent/ErrorComponent.js
  src/components/ErrorComponent/index.js
  src/components/FolderInfo/FolderInfo.css
  src/components/FolderInfo/FolderInfo.js
  src/components/FolderInfo/index.js
  src/components/FolderTitle/FolderTitle.css
  src/components/FolderTitle/FolderTitle.js
  src/components/FolderTitle/index.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/index.js
  src/components/GlobalStyles.js
  src/components/Header.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/index.js
  src/components/LinkInput.css
  src/components/LinkInput.js
  src/components/LinkInput/LinkInput.css
  src/components/LinkInput/LinkInput.js
  src/components/LinkInput/index.js
  src/components/LinkList.js
  src/components/LinkList/LinkList.js
  src/components/LinkList/Linklist.css
  src/components/LinkList/index.js
  src/components/Linklist.css
  src/components/ListItem/ListItem.js
  src/components/ListItem/index.js
  src/components/ModalLayout/ModalLayout.css
  src/components/ModalLayout/ModalLayout.js
  src/components/ModalLayout/index.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/components/SearchBar/index.js
  src/components/SharedPage.css
  src/components/Sorting.css
  src/components/Sorting.js
  src/components/Sorting/Sorting.css
  src/components/Sorting/Sorting.js
  src/components/Sorting/index.js
  src/components/index.js
  src/pages/FolderPage.js
  src/pages/SharedPage.js
  src/util/api.js
  src/util/index.js
  src/util/url.js
  src/util/util.js
Labels: 매운맛🔥, 미완성🫠

#355 [이진욱] Week11
  package-lock.json
  package.json
  public/_redirects
  src/assets/icons/cancel.svg
  src/assets/icons/check.svg
  src/assets/icons/facebook_icon.svg
  src/assets/icons/toast-check.svg
  src/assets/icons/toast-close.svg
  src/components/AddLink/AddLink.jsx
  src/components/AddLink/AddLink.styled.js
  src/components/Button/Button.jsx
  src/components/Button/Button.styled.js
  src/components/Card/Card.jsx
  src/components/Card/Card.styled.js
  src/components/Card/Kebab.jsx
  src/components/Card/Kebab.styled.js
  src/components/Card/Kebob.jsx
  src/components/Folder/Folder.jsx
  src/components/Folder/Folder.styled.js
  src/components/Folder/FolderOptionButton.jsx
  src/components/Folder/FolderOptionButton.styled.js
  src/components/Folder/FolderSelectButton.styled.js
  src/components/Footer/Footer.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.styled.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.styled.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.styled.js
  src/components/Nav/UserLoggedIn.styled.js
  src/components/Toast/Toast.jsx
  src/components/Toast/Toast.styled.js
  src/hooks/useToggle.js
  src/pages/FolderPage.jsx
  src/pages/HomePage.jsx
  src/pages/HomePage.styled.js
  src/styles/Global.styled.js
  src/utils/CalculateTime.js
  src/utils/clipboard.js
Labels: 미완성🫠

#387 [오다은] Week11
  public/_redirects
  public/css/global.css
  public/css/reset.css
  public/css/utils.css
  public/index.html
  src/api.js
  src/assets/add_icon.png
  src/assets/add_icon.svg
  src/assets/add_white_icon.png
  src/assets/add_white_icon.svg
  src/assets/check_icon.svg
  src/assets/close_button.svg
  src/assets/share_facebook.svg
  src/assets/share_kakaotalk.svg
  src/assets/share_link.svg
  src/components/Button/Button.js
  src/components/Button/Button.jsx
  src/components/Button/Button.styled.js
  src/components/Card/Card.js
  src/components/Card/Card.jsx
  src/components/Card/Card.styled.js
  src/components/CardList/CardList.jsx
  src/components/CardList/CardList.styled.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.styled.js
  src/components/Footer/FooterSnsItem.jsx
  src/components/Header/Header.js
  src/components/Header/Header.jsx
  src/components/Header/Header.styled.js
  src/components/LinkInput/LinkInput.js
  src/components/LinkInput/LinkInput.jsx
  src/components/LinkInput/LinkInput.styled.js
  src/components/MenuButton/MenuButton.js
  src/components/MenuButton/MenuButton.jsx
  src/components/MenuButton/MenuButton.styled.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.styled.js
  src/components/Profile/Profile.js
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.styled.js
  src/components/Search/Search.js
  src/components/Search/Search.jsx
  src/components/Search/Search.styled.js
  src/pages/Common.styled.js
  src/pages/FolderPage/FolderPage.js
  src/pages/FolderPage/FolderPage.jsx
  src/pages/FolderPage/FolderPage.styled.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.styled.js
  src/pages/SharedPage/SharedPage.js
  src/pages/SharedPage/SharedPage.jsx
  src/pages/SharedPage/SharedPage.styled.js
Labels: 매운맛🔥, 미완성🫠

#374 [조혜진] Week12
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Article/Article.tsx
  src/Components/Cards/Cards.tsx
  src/Components/FolderInfo/FolderInfo.tsx
  src/Components/FolderMain/FolderMain.module.css
  src/Components/FolderMain/FolderMain.tsx
  src/Components/Footer/Footer.module.css
  src/Components/Footer/Footer.tsx
  src/Components/Header/Header.tsx
  src/Components/Modal/Modal.tsx
  src/Components/SharedMain/SharedMain.tsx
  src/api/parseData.tsx
  src/assets/_close.png
  src/constants/baseURL.tsx
  src/folder.tsx
  src/hooks/useFetch.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/shared.tsx
  src/sign/signin.html
  src/sign/signin.ts
  src/sign/signup.ts
  src/utils/formatDate.tsx
  tsconfig.json
  vite.config.ts
Labels: 매운맛🔥

#391 [장문원] week11
  package-lock.json
  package.json
  src/App.js
  src/assets/close.png
  src/assets/close.svg
  src/assets/delete.svg
  src/assets/kebab.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/star.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/constant.js
  src/components/Header/Header.jsx
  src/components/KebabButton/KebabButton.css
  src/components/KebabButton/KebabButton.jsx
  src/components/NavigationBar/NavigationBar.jsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.module.scss
  src/hooks/useAsync.js
  src/hooks/useFetchUser.jsx
  src/hooks/useGetUser.js
  src/index.js
  src/pages/Folder/FolderPage.css
  src/pages/Folder/FolderPage.jsx
  src/pages/FolderList/FolderList.css
  src/pages/FolderList/FolderList.jsx
  src/pages/Home/HomePage.jsx
  src/sharing/ui-layout/Layout.jsx
  src/sharing/ui-layout/Layout.module.scss
  src/sharing/ui-modal-layout/LinkDeletModal.jsx
  src/sharing/ui-modal-layout/LinkDeletModal.module.scss
  src/styles/color.scss
  src/styles/global.scss
  src/styles/resets.css
  src/util/constant.js
  src/util/getElapsedTime.js
Labels: 미완성🫠, 순한맛🐑

#392 [김보민] Week12
  jsconfig.json
  netlify.toml
  public/_redirects
  public/images/check.svg
  src/components/FolderInfo/FolderInfo.js
  src/components/FolderTitle/FolderTitle.js
  src/components/Header/Header.js
  src/components/LinkInput/LinkInput.css
  src/components/LinkInput/LinkInput.js
  src/components/LinkList/LinkList.js
  src/components/ListItem/ListItem.js
  src/components/ModalLayout/ModalLayout.css
  src/components/ModalLayout/ModalLayout.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/components/Sorting/Sorting.js
  src/hooks/index.js
  src/hooks/useSearch.js
  src/pages/FolderPage.js
  src/util/calculator.js
  src/util/index.js
Labels: 매운맛🔥, 미완성🫠

#375 [정지성] week12
  README.md
  package-lock.json
  package.json
  pull_request_template.md
  src/components/Addlink/index.tsx
  src/components/Cards/index.tsx
  src/components/Cardsfolder/index.tsx
  src/components/Folderdata/index.tsx
  src/components/Foldermenu/index.tsx
  src/components/Footer/index.jsx
  src/components/Footer/index.tsx
  src/components/Main.tsx
  src/components/Navigation/index.tsx
  src/components/SearchBar/index.tsx
  src/components/SearchableBar/index.module.css
  src/components/SearchableBar/index.tsx
  src/components/index.js
  src/hooks/date.ts
  src/hooks/useFetch.ts
  src/modal/ModalAddToFolder.jsx
  src/modal/ModalAddToFolder.tsx
  src/modal/ModalDelete.jsx
  src/modal/ModalDelete.tsx
  src/modal/ModalFolder.jsx
  src/modal/ModalFolder.tsx
  src/modal/ModalShare.jsx
  src/modal/ModalShare.tsx
  src/pages/FolderPage.tsx
  src/pages/SharedPage.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/utils/hooks/date.js
  tsconfig.json
Labels: 미완성🫠, 순한맛🐑

#381 [김미소] week11
  public/assets/icon/icon_check.svg
  public/assets/icon/icon_close.png
  public/assets/icon/icon_close.svg
  src/components/common/Header.tsx
  src/components/common/atoms/Button.tsx
  src/components/common/atoms/CheckBox.tsx
  src/components/common/atoms/Input.tsx
  src/components/common/atoms/buttonStyle.ts
  src/components/common/atoms/checkBoxStyle.ts
  src/components/common/atoms/inputStyle.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/interface.ts
  src/components/common/modal/modalStyle.ts
  src/components/folder/ContantList.tsx
  src/components/folder/FolderButtonList.tsx
  src/components/folder/FolderContentControll.tsx
  src/components/folder/LinkAddHeader.tsx
  src/components/folder/PostCard.tsx
  src/components/folder/SearchInputBox.tsx
  src/components/share/ShareModal.tsx
  src/components/share/shareStyle.ts
  src/constant/modal.ts
  src/constant/share.ts
  src/hook/useFetch.tsx
  src/pages/folder/Index.tsx
  src/pages/folder/Shared.tsx
  src/pages/folder/folderStyle.ts
  src/pages/folder/interface.ts
  src/styles/commonStyle.ts
  src/styles/globalStyle.ts
Labels: 매운맛🔥, 미완성🫠

#388 [김은재] Week11
  public/index.html
  src/assets/fonts/Inter.woff
  src/assets/icon/check.svg
  src/assets/icon/icon_share_facebook.svg
  src/assets/icon/icon_share_kakao.svg
  src/assets/icon/icon_share_link.svg
  src/assets/icon/modal_close.svg
  src/components/common/Button.jsx
  src/components/common/Button.styled.jsx
  src/components/common/KebabList.jsx
  src/components/common/Link.jsx
  src/components/common/modal/ModalLayout.jsx
  src/components/common/modal/ModalLayout.styled.jsx
  src/components/common/modal/ModalPortal.jsx
  src/components/common/modal/modalContent/FolderAddModalContent.jsx
  src/components/common/modal/modalContent/FolderAddModalContent.styled.jsx
  src/components/common/modal/modalContent/FolderDeleteContent.jsx
  src/components/common/modal/modalContent/FolderNameChangeContent.jsx
  src/components/common/modal/modalContent/FolderNameChangeContent.styled.jsx
  src/components/common/modal/modalContent/LinkAddContent.jsx
  src/components/common/modal/modalContent/LinkAddContent.styled.jsx
  src/components/common/modal/modalContent/LinkDeleteContent.jsx
  src/components/common/modal/modalContent/ShareModalContent.jsx
  src/components/common/modal/modalContent/ShareModalContent.styled.jsx
  src/components/folder/LinkAdd.jsx
  src/components/folder/NavBox.jsx
  src/components/folder/NavBox.styled.jsx
  src/context/Modal.js
  src/hooks/useMoadlScrollBlock.js
  src/hooks/useModal.js
  src/index.js
Labels: 매운맛🔥

#363 [권주현] Week11
  public/favicon.ico
  public/index.html
  src/assets/facebook.png
  src/assets/kakaotalk.png
  src/assets/share.png
  src/global.css
  src/globalComponents/Avatar/Avatar.module.css
  src/globalComponents/Avatar/index.jsx
  src/globalComponents/Footer/Footer.module.css
  src/globalComponents/Footer/index.jsx
  src/globalComponents/Header/Header.module.css
  src/globalComponents/Header/index.jsx
  src/globalComponents/Modal/Modal.module.css
  src/globalComponents/Modal/ModalChildren.module.css
  src/globalComponents/Modal/index.jsx
  src/globalComponents/SearchBar/SearchBar.module.css
  src/globalComponents/SearchBar/index.jsx
  src/pages/FolderPage/components/FolderController/FoldersController.module.css
  src/pages/FolderPage/components/FolderController/index.jsx
  src/pages/FolderPage/components/FolderLinkCard.jsx
  src/pages/FolderPage/components/FolderLinkCard/components/LinkAddToFolderForm/index.jsx
  src/pages/FolderPage/components/FolderLinkCard/components/LinkDeleteForm/index.jsx
  src/pages/FolderPage/components/FolderLinkCard/index.jsx
  src/pages/FolderPage/components/FolderLinkCards/index.jsx
  src/pages/FolderPage/components/FoldersList.jsx
  src/pages/FolderPage/components/FoldersList/FoldersList.module.css
  src/pages/FolderPage/components/FoldersList/components/FolderAddForm/index.jsx
  src/pages/FolderPage/components/FoldersList/components/FolderDeleteForm/index.jsx
  src/pages/FolderPage/components/FoldersList/components/FolderEditForm/index.jsx
  src/pages/FolderPage/components/FoldersList/components/SocialShareBox/index.jsx
  src/pages/FolderPage/components/FoldersList/index.jsx
  src/pages/FolderPage/components/LinkAddForm/LinkAddForm.module.css
  src/pages/FolderPage/components/LinkAddForm/index.jsx
  src/pages/FolderPage/index.jsx
  src/pages/LinkCard.module.css
  src/pages/LinkCards.module.css
  src/pages/SharedPage/components/SharedLinkCard/index.jsx
  src/pages/SharedPage/components/SharedLinkCards/SharedLinkCards.jsx
  src/pages/SharedPage/components/UserProfileAndTitle/UserProfileAndTitle.module.css
  src/pages/SharedPage/components/UserProfileAndTitle/index.jsx
  src/pages/SharedPage/index.jsx
Labels: 매운맛🔥

#390 [김한샘] Week12
  package-lock.json
  package.json
  src/App.tsx
  src/components/AddLinkForm/AddLinkForm.tsx
  src/components/Card/Card.tsx
  src/components/Card/EditableStarButton.tsx
  src/components/Card/KebabButton.tsx
  src/components/Card/KebabList.tsx
  src/components/CardList/CardList.jsx
  src/components/CardList/CardList.tsx
  src/components/CardTitleIcon/CardTitleIcon.tsx
  src/components/ConHeader/ConHeader.jsx
  src/components/ConHeader/ConHeader.tsx
  src/components/FolderTabList/Button.jsx
  src/components/FolderTabList/Button.tsx
  src/components/FolderTabList/FolderAddButton.tsx
  src/components/FolderTabList/FolderTabList.tsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.jsx
  src/components/Header/Header.tsx
  src/components/Modal/FolderAddModal/FolderAddButton.tsx
  src/components/Modal/FolderAddModal/FolderAddModal.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalContext.jsx
  src/components/Modal/ModalContext.tsx
  src/components/Modal/ShareModal.tsx
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.tsx
  src/components/Search/Search.jsx
  src/components/Search/Search.tsx
  src/custom.d.ts
  src/fetchUtils/index.js
  src/fetchUtils/index.ts
  src/hooks/useModal.tsx
  src/hooks/useToggle.jsx
  src/hooks/useToggle.tsx
  src/index.jsx
  src/index.tsx
  src/pages/Folder.tsx
  src/pages/NotFoundPage.jsx
  src/pages/NotFoundPage.tsx
  src/pages/Shared.jsx
  src/pages/Shared.tsx
  src/routes/index.jsx
  src/routes/index.tsx
  src/utils/GetDate.js
  src/utils/GetDate.ts
  src/utils/GetDaysAgo.js
  src/utils/GetDaysAgo.ts
  tsconfig.json
Labels: 미완성🫠

#394 [김법균] week12
  README.md
  craco.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/assets/images/delete_text.png
  src/components/Account/Account.tsx
  src/components/AddLinkBar/AddLinkBar.jsx
  src/components/AddLinkBar/AddLinkBar.module.css
  src/components/AddLinkBar/AddLinkBar.tsx
  src/components/Button/Button.tsx
  src/components/FolderInfo/FolderInfo.tsx
  src/components/FolderPageContent/FolderPageContent.css
  src/components/FolderPageContent/FolderPageContent.tsx
  src/components/FolderToolBar/FolderToolBar.tsx
  src/components/FolderToolBar/FolderToolBarButton.jsx
  src/components/FolderToolBar/FolderToolBarButton.tsx
  src/components/FolderToolBar/UtilButton.jsx
  src/components/FolderToolBar/UtilButton.tsx
  src/components/FolderToolBar/constants.ts
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/LinkCard/LinkCard.tsx
  src/components/LinkCardList/LinkCardList.jsx
  src/components/LinkCardList/LinkCardList.module.css
  src/components/LinkCardList/LinkCardList.tsx
  src/components/Modal/Modal.module.css
  src/components/Modal/Modal.tsx
  src/components/ModalContents/AddToFolderModal.tsx
  src/components/ModalContents/DeleteModal.tsx
  src/components/ModalContents/FolderInputModal.tsx
  src/components/ModalContents/ModalContents.module.css
  src/components/ModalContents/ShareModal.jsx
  src/components/ModalContents/ShareModal.tsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.tsx
  src/index.css
  src/index.jsx
  src/pages/FolderPage/FolderPage.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/utils/api.ts
  src/utils/convertObjectKeysToCamelCase.js
  src/utils/convertObjectKeysToCamelCase.ts
  src/utils/interfaces.ts
  src/utils/mockData.js
  src/utils/shareFunctions/facebooShare.ts
  src/utils/shareFunctions/kakaoshare.ts
  src/utils/time-functions/formatDate.ts
  src/utils/time-functions/getTimeDifference.ts
  tsconfig.json
  tsconfig.paths.json
Labels: 매운맛🔥

#403 [김다진] week 8
  part 2/package-lock.json
  part 2/package.json
  part 2/src/App.js
  part 2/src/component/api/folderApi.js
  part 2/src/component/api/userApi.js
  part 2/src/component/api/usersFoldersApi.js
  part 2/src/component/api/usersLinksApi.js
  part 2/src/component/card.css
  part 2/src/component/folder/filterButtons.css
  part 2/src/component/folder/filterButtons.jsx
  part 2/src/component/folder/folderCard.jsx
  part 2/src/component/folder/folderCardList.jsx
  part 2/src/component/folder/folderMain.jsx
  part 2/src/component/folder/linkAddInput.css
  part 2/src/component/folder/linkAddInput.jsx
  part 2/src/component/header.css
  part 2/src/component/header.jsx
  part 2/src/component/main.css
  part 2/src/component/shared/card.jsx
  part 2/src/component/shared/cardList.css
  part 2/src/component/shared/cardList.jsx
  part 2/src/component/shared/cardListSearch.css
  part 2/src/component/shared/cardListSearch.jsx
  part 2/src/component/shared/sharedMain.jsx
  part 2/src/component/shared/title.css
  part 2/src/component/shared/title.jsx
  part 2/src/icon/add.svg
  part 2/src/icon/delete.svg
  part 2/src/icon/kebab.svg
  part 2/src/icon/link.svg
  part 2/src/icon/pen.svg
  part 2/src/icon/share.svg
  part 2/src/icon/star.svg
  part 2/src/img/이미지 없을 때 배경.svg
  part 2/src/pages/folder.jsx
  part 2/src/pages/shared.jsx
Labels: 매운맛🔥

#409 [유호민] Week13
  .gitignore
  component/AddLinkInput.tsx
  component/FolderMain.tsx
  component/Footer.tsx
  component/Hero.tsx
  component/LandingDescription.tsx
  component/LinkCard.tsx
  component/LinkCardByFolderId.tsx
  component/LinkCardList.tsx
  component/LinkCardListByFolderId.tsx
  component/Modal.tsx
  component/Navbar.tsx
  component/User.tsx
  hooks/useCurrentUser.ts
  hooks/useSampleFolder.ts
  hooks/useUserFolders.ts
  hooks/useUserLinks.ts
  hooks/useUserLinksById.ts
  lib/fetcher.ts
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/api.ts
  pages/api/hello.ts
  pages/api/input.ts
  pages/api/user.ts
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  postcss.config.js
  public/images/avatar.svg
  public/images/close.svg
  public/images/delete.svg
  public/images/dog.png
  public/images/edit-folder.png
  public/images/facebook.svg
  public/images/hero.png
  public/images/instagram.svg
  public/images/kakao.svg
  public/images/kebab.svg
  public/images/link.svg
  public/images/logo.svg
  public/images/no-image.svg
  public/images/pen.svg
  public/images/profile.svg
  public/images/search-folder.png
  public/images/search.svg
  public/images/share-folder.png
  public/images/share.svg
  public/images/twitter.svg
  public/images/youtube.svg
  styles/globals.css
  tailwind.config.js
  utils/calculateTimeDiff.ts
  utils/formatDate.ts
Labels: 미완성🫠, 순한맛🐑

#417 [권주현] Week13
  .gitignore
  README.md
  components/Avatar/Avatar.module.css
  components/Avatar/index.tsx
  components/FolderController/FoldersController.module.css
  components/FolderController/index.tsx
  components/FolderLinkCard/index.tsx
  components/FolderLinkCards/index.tsx
  components/FoldersList/FoldersList.module.css
  components/FoldersList/index.tsx
  components/Footer/Footer.module.css
  components/Footer/index.tsx
  components/Header/Header.module.css
  components/Header/index.tsx
  components/Input/Input.module.css
  components/Input/index.tsx
  components/LinkAddForm/LinkAddForm.module.css
  components/LinkAddForm/index.tsx
  components/LinkCard.module.css
  components/LinkCards.module.css
  components/Modal/Modal.module.css
  components/Modal/childrens/FolderAddForm/index.tsx
  components/Modal/childrens/FolderDeleteForm/index.tsx
  components/Modal/childrens/FolderEditForm/index.tsx
  components/Modal/childrens/LinkAddToFolderForm/index.tsx
  components/Modal/childrens/LinkDeleteForm/index.tsx
  components/Modal/childrens/ModalChildren.module.css
  components/Modal/childrens/SocialShareBox/index.tsx
  components/Modal/index.tsx
  components/SearchBar/SearchBar.module.css
  components/SearchBar/index.tsx
  components/SharedLinkCard/index.tsx
  components/SharedLinkCards/SharedLinkCards.tsx
  components/UserProfileAndTitle/UserProfileAndTitle.module.css
  components/UserProfileAndTitle/index.tsx
  lib/api.ts
  lib/constants.ts
  lib/dateUtils.ts
  lib/useAsync.ts
  next.config.mjs
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  public/Linkbrary.png
  public/card-default.png
  public/facebook.png
  public/kakaotalk.png
  public/share.png
  styles/global.css
  tsconfig.json
Labels: 매운맛🔥

#423 [김법균] Week13
  components/AuthHeader/AuthHeader.module.css
  components/AuthHeader/AuthHeader.tsx
  components/Button/Button.module.css
  components/Button/Button.tsx
  components/Footer/Footer.module.css
  components/Footer/Footer.tsx
  components/Header/Header.module.css
  components/Header/Header.tsx
  components/SignInForm/SignInForm.tsx
  components/SignUpForm/SignUpForm.tsx
  components/SocialAuth/SocialAuth.module.scss
  components/SocialAuth/SocialAuth.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/assets/images/eye-off.svg
  public/assets/images/eye-on.svg
  public/assets/images/facebook_logo.svg
  public/assets/images/feature1.png
  public/assets/images/feature2.png
  public/assets/images/feature3.png
  public/assets/images/feature4.png
  public/assets/images/google.svg
  public/assets/images/homeImage.png
  public/assets/images/instagram_logo.svg
  public/assets/images/kakao.svg
  public/assets/images/logo.svg
  public/assets/images/twitter_logo.svg
  public/assets/images/youtube_logo.svg
  styles/AuthForm.module.scss
  styles/AuthPage.module.css
  styles/Home.module.css
  styles/globals.css
  styles/mixins.scss
  styles/reset.css
  utils/validateEmail.ts
Labels: 미완성🫠

#444 [황은지] week14
  weekly/assets/icon-google.svg
  weekly/assets/icon-kakaotalk.svg
  weekly/components/Auth/Logo.tsx
  weekly/components/Auth/SignInput.tsx
  weekly/components/Auth/SignLabel.tsx
  weekly/components/Auth/Social.tsx
  weekly/components/Auth/SocialIcon.tsx
  weekly/components/Button/GradientButton.tsx
  weekly/components/Common/Footer.js
  weekly/components/Common/Nav.js
  weekly/components/Common/NoLink.js
  weekly/components/Common/Profile.js
  weekly/components/FolderPage/AddLink.js
  weekly/components/FolderPage/CardList.js
  weekly/components/FolderPage/Folder.js
  weekly/components/FolderPage/FolderToolBar.js
  weekly/components/FolderPage/Search.js
  weekly/next.config.mjs
  weekly/package-lock.json
  weekly/package.json
  weekly/pages/FolderPage.js
  weekly/pages/_app.tsx
  weekly/pages/index.tsx
  weekly/pages/shared.js
  weekly/pages/signin.tsx
  weekly/pages/signup.tsx
  weekly/static/fonts/PretendardVariable.woff2
  weekly/styles/Global.css
  weekly/utils/isValidEmail.tsx
Labels: 미완성🫠

#447 [김한샘] week14
  .env
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  src/assets/images/main/sec01_img.png
  src/assets/images/main/sec02_img1.png
  src/assets/images/main/sec02_img2.png
  src/assets/images/main/sec02_img3.png
  src/assets/images/main/sec02_img4.png
  src/components/AddLinkForm/AddLinkForm.tsx
  src/components/AuthContainer/AuthContainer.tsx
  src/components/AuthHeader/index.tsx
  src/components/AuthIconButton/AuthIconButton.tsx
  src/components/Card/Card.tsx
  src/components/CardList/CardList.tsx
  src/components/ConHeader/ConHeader.tsx
  src/components/FolderTabList/Button.tsx
  src/components/FolderTabList/FolderTabList.tsx
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/Main/Main.module.css
  src/components/Main/Main.tsx
  src/components/Modal/ModalContext.tsx
  src/components/Modal/ShareModal.tsx
  src/components/Profile/Profile.tsx
  src/components/SocialLogin/SocialLogin.tsx
  src/fetchUtils/axiosInstance.ts
  src/fetchUtils/index.ts
  src/types/folder/folder.ts
  src/types/login.ts
  src/utils/GetDate.ts
  src/utils/GetDaysAgo.ts
  src/utils/validation.ts
  src/widgets/signIn/Auth.module.css
  src/widgets/signIn/SignInForm/SignInForm.tsx
  src/widgets/signIn/index.tsx
  src/widgets/signup/SignUpForm/SignUpForm.tsx
  src/widgets/signup/index.tsx
  styles/form.css
Labels: 매운맛🔥

#455 [정성혜] week14
  .github/pull_request_template.md
  .gitignore
  README.md
  assets/icons/add.svg
  assets/icons/check.svg
  assets/icons/close.svg
  assets/icons/eye-off.svg
  assets/icons/eye-on.svg
  assets/icons/facebook.svg
  assets/icons/instagram.svg
  assets/icons/kakao.svg
  assets/icons/kebab.svg
  assets/icons/link.svg
  assets/icons/linkbrary.svg
  assets/icons/pen.svg
  assets/icons/search.svg
  assets/icons/share.svg
  assets/icons/star.svg
  assets/icons/trash.svg
  assets/icons/twitter.svg
  assets/icons/youtube.svg
  assets/images/card-default.png
  components/Button/Button.styled.ts
  components/Button/Button.tsx
  components/Eye/Eye.tsx
  components/Input/Input.styled.ts
  components/Input/Input.tsx
  components/SignIn/SignIn.styled.ts
  components/SignIn/SignIn.tsx
  components/SignUp/SignUp.styled.ts
  components/SignUp/SignUp.tsx
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/hello.js
  pages/index.js
  styles/Home.module.css
  styles/globals.css
Labels: 미완성🫠

#427 [김다진] week11
  part 2/.stylelintrc.json
  part 2/src/component/api/usersFoldersApi.js
  part 2/src/component/card.css
  part 2/src/component/cardList.css
  part 2/src/component/folder/filterButtons.jsx
  part 2/src/component/folder/folderCard.jsx
  part 2/src/component/folder/folderCardList.jsx
  part 2/src/component/folder/folderMain.jsx
  part 2/src/component/folder/linkAddInput.css
  part 2/src/component/folder/linkAddInput.jsx
  part 2/src/component/folder/modal/modal.css
  part 2/src/component/folder/modal/modal.jsx
  part 2/src/component/folder/toolBar.css
  part 2/src/component/folder/toolBar.jsx
  part 2/src/component/header.jsx
  part 2/src/component/main.css
  part 2/src/component/shared/card.jsx
  part 2/src/component/shared/cardList.jsx
  part 2/src/component/shared/title.jsx
  part 2/src/globalStyle.css
  part 2/src/icon/_close.svg
Labels: 매운맛🔥, 미완성🫠

#448 [우지석] Week14
  components/EmailInput.tsx
  components/PasswordInput.tsx
  components/SignInForm.tsx
  components/SignUpForm.tsx
  components/SignUpPassword.tsx
  components/passwordToggle.js
  package-lock.json
  package.json
  pages/_document.tsx
  pages/api/hello.ts
  pages/folder.tsx
  pages/index.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/favicon.ico
  public/img/Linkbrary.jpg
  public/img/facebook.svg
  public/img/google.svg
  public/img/instagram.svg
  public/img/kakao.svg
  public/img/logo.svg
  public/img/main.png
  public/img/manage.png
  public/img/meta.png
  public/img/save.png
  public/img/search.png
  public/img/share.png
  public/img/twitter.svg
  public/img/youtube.svg
  public/next.svg
  public/vercel.svg
  styles/Home.module.css
  styles/Home.module.scss
  styles/globals.css
  styles/signin.module.scss
  styles/signup.module.scss
Labels: 매운맛🔥, 미완성🫠

#431 [홍진호] week14
  app/(auth)/_components/footer.tsx
  app/(auth)/layout.tsx
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/page.tsx
  bun.lockb
  components/logo.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  lib/utils.ts
  package.json
  public/google.png
  public/kakao.png
Labels: 순한맛🐑

#445 [김미소] week14
  .babelrc
  components/common/Footer.tsx
  components/common/Header.tsx
  components/common/SocialLinkButton.tsx
  components/common/atoms/Button.tsx
  components/common/atoms/CheckBox.tsx
  components/common/atoms/Input.tsx
  components/common/atoms/LinkButton.tsx
  components/common/atoms/LinkButtonStyle.ts
  components/common/atoms/buttonStyle.ts
  components/common/atoms/inputStyle.ts
  components/common/footerStyle.ts
  components/common/headerStyle.ts
  components/folder/FolderButtonList.tsx
  components/folder/FolderContentControll.tsx
  components/folder/LinkAddHeader.tsx
  components/folder/PostCard.tsx
  components/folder/PostCardList.tsx
  components/folder/PostCardStyle.ts
  components/folder/SearchInputBox.tsx
  components/folder/interface.ts
  components/join/formStyle.ts
  components/join/interfase.ts
  components/loading/Loading.tsx
  components/loading/loading.module.css
  components/modal/Modal.tsx
  components/modal/interface.ts
  components/share/ShareModal.tsx
  components/share/shareStyle.ts
  lib/auto.context.tsx
  lib/axios.ts
  next.config.js
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/faq/index.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/mainStyle.ts
  pages/policy/index.tsx
  pages/shared/[id].tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  src/constant/api.ts
  src/constant/layoutConfig.ts
  src/constant/modal.ts
  src/constant/share.ts
  src/utils/calcTilmAgo.ts
  styles/commonStyle.ts
  styles/errorStyle.ts
  styles/folderStyle.ts
  styles/loginStyle.ts
  styles/mainStyle.ts
  styles/styled.d.ts
  styles/theme.ts
Labels: 매운맛🔥

#437 [정지성] week14
  components/Cards/index.tsx
  components/FolderCards/index.module.css
  components/FolderCards/index.tsx
  components/Folderdata/index.module.css
  components/Folderdata/index.tsx
  components/Foldermenu/foldermenu.module.css
  components/Foldermenu/index.tsx
  components/Footer/index.tsx
  components/IdInput/index.module.css
  components/IdInput/index.tsx
  components/Navigation/index.module.css
  components/Navigation/index.tsx
  components/PasswordInput/index.module.css
  components/PasswordInput/index.tsx
  components/ShareCards/index.module.css
  components/ShareCards/index.tsx
  components/modal/ModalDelete.tsx
  components/modal/modalDelete.module.css
  constant/folder-constant.js
  constant/footer-constant.ts
  constant/navigation-constant.js
  constant/shared-constant.js
  constant/signin-constant.js
  constant/signup-constant.js
  constant/testuser.js
  hooks/useSignInId.ts
  hooks/useSignInPwd.ts
  hooks/useSignUpId.ts
  hooks/useSignUpPwd.ts
  hooks/useSignUpPwdCheck.ts
  next.config.js
  pages/folder/index.tsx
  pages/shared/index.module.css
  pages/shared/index.tsx
  pages/signin/index.module.css
  pages/signin/index.tsx
  pages/signup/index.module.css
  pages/signup/index.tsx
  pages/test/index.tsx
  utils/date.ts
  utils/emailRegrex.js
Labels: 매운맛🔥

#442 [고학영] week14
  .gitignore
  api/Auth.jsx
  components/AddFolderButton.tsx
  components/AddLinkInput.tsx
  components/AuthForm.module.css
  components/AuthFormHeader.module.css
  components/AuthFormHeader.tsx
  components/CardListSection.tsx
  components/FolderEditMenu.module.css
  components/FolderEditMenu.tsx
  components/FolderList.module.css
  components/FolderList.tsx
  components/FolderMenu.module.css
  components/FolderMenu.tsx
  components/KebabMenu.tsx
  components/PasswordToggleButton.module.css
  components/PasswordToggleButton.tsx
  components/SigninForm.tsx
  components/SignupForm.tsx
  components/SocialAuthForm.module.css
  components/SocialAuthForm.tsx
  hooks/useIsMobile.tsx
  modals/AddLinkToFolder.tsx
  modals/DeleteFolder.tsx
  modals/EditAndAddFolder.tsx
  modals/ShareFolder.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_document.tsx
  pages/auth.module.css
  pages/folder.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/Google.svg
  public/Kakao.svg
  public/eye-off.svg
  public/eye-on.svg
  tsconfig.json
Labels: 매운맛🔥

#443 [오다은] Week14
  apis/api.ts
  components/Header/Header.tsx
  components/Profile/Profile.styled.ts
  contexts/UserContext.tsx
  hooks/useAsync.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  src/images/login_google.png
  src/images/login_google.svg
  src/images/login_kakaotalk.png
  src/images/login_kakaotalk.svg
  styles/Auth.styled.tsx
  styles/CommonPage.styled.ts
  styles/HomePage.styled.ts
  styles/globals.styled.ts
  utils/validate.ts
Labels: 매운맛🔥, 미완성🫠

#454 [김보민] week14
  .DS_Store
  components/FolderInfo/FolderInfo.js
  components/InputBox/InputBox.js
  components/InputBox/InputBox.module.scss
  components/InputBox/constants.js
  components/InputBox/index.js
  components/SinginForm/SinginForm.js
  components/SinginForm/SinginForm.module.scss
  components/SinginForm/index.js
  components/SingupForm/SingupForm.js
  components/SingupForm/SingupForm.module.scss
  components/SingupForm/index.js
  components/SocalLogin/SocalLogin.js
  components/SocalLogin/SocalLogin.module.scss
  components/SocalLogin/index.js
  css/reset.css
  css/signin.css
  css/style.css
  images/99FE484C5C3451F218 1.svg
  images/Card 1.png
  images/Card-1.png
  images/Card.png
  images/Group 20.svg
  images/Kakao.svg
  images/akar-icons_facebook-fill.svg
  images/akar-icons_twitter-fill.svg
  images/akar-icons_youtube-fill.svg
  images/ant-design_instagram-filled.svg
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/google.svg
  images/image 25.png
  images/image25.png
  images/logo.svg
  images/스크린샷 2023-03-17 오후 3.22 1.png
  images/디스크립션 없는 팝업 1.png
  images/스크린샷 2023-03-17 오후 3.22 1.png
  images/폴더 공유하기 팝업 1.png
  package-lock.json
  package.json
  pages/signin.js
  pages/signup.js
  styles/giobal.css
  styles/sign.module.scss
  utils/api.js
  utils/constants.js
  utils/index.js
  utils/url.js
Labels: 매운맛🔥, 미완성🫠

#446 [이진욱] Week14
  .env.production
  .github/workflows/delete-merged-branch-config.yml
  components/AddLink/AddLink.tsx
  components/App/AppLayout.tsx
  components/Button/Button.tsx
  components/Card/Card.tsx
  components/CloseButton/CloseButton.tsx
  components/DropDown/DropDownContents/LinkMenu.styled.ts
  components/DropDown/DropDownContents/LinkMenu.tsx
  components/Eye/Eye.tsx
  components/Folder/Folder.tsx
  components/Folder/FolderOwner.styled.ts
  components/Folder/FolderOwner.tsx
  components/FolderOptionButton/FolderOptionButton.styled.ts
  components/FolderOptionButton/FolderOptionButton.tsx
  components/Footer/Footer.tsx
  components/Input/Input.styled.ts
  components/Input/Input.tsx
  components/KakaoButton/KakaoButton.tsx
  components/Kebab/Kebab.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalContents/AddFolder.tsx
  components/Modal/ModalContents/AddLinkToFolder.tsx
  components/Modal/ModalContents/BasicModal.tsx
  components/Modal/ModalContents/ChangeName.tsx
  components/Modal/ModalContents/DeleteFolder.tsx
  components/Modal/ModalContents/DeleteLink.tsx
  components/Modal/ModalContents/ShareFolder.tsx
  components/Modal/ModalTypes.tsx
  components/Nav/Nav.tsx
  components/Search/Search.tsx
  components/Star/Star.styled.ts
  components/Star/Star.tsx
  components/Toast/Toast.styled.ts
  components/Toast/Toast.tsx
  components/Toast/ToastTypes.tsx
  constants/strings.ts
  hooks/useAsync.ts
  pages/_app.tsx
  pages/folderPage.tsx
  pages/index.tsx
  pages/landingPage.tsx
  pages/sharedPage/[folderId].tsx
  pages/signIn.tsx
  pages/signUp.tsx
  redux/actions/auth.ts
  redux/actions/folder.ts
  redux/actions/link.ts
  redux/reducers/auth.ts
  redux/reducers/folder.ts
  redux/reducers/link.ts
  redux/reducers/modal.ts
  services/axiosInstace.ts
  services/types.ts
  styles/landingPage.styled.ts
  utils/calculateTime.ts
Labels: 매운맛🔥

#459 [김은재] Week14
  api/folder.ts
  api/header.ts
  api/user.ts
  components/common/Button.styled.ts
  components/common/Button.tsx
  components/common/KebabList.styled.ts
  components/common/Link.tsx
  components/common/LinkList.tsx
  components/common/modal/modalContent/FolderAddModalContent.tsx
  components/common/modal/modalContent/FolderDeleteContent.tsx
  components/common/modal/modalContent/LinkAddContent.styled.ts
  components/common/modal/modalContent/LinkAddContent.tsx
  components/common/modal/modalContent/ShareModalContent.tsx
  components/folder/LinkAdd.styled.ts
  components/folder/LinkAdd.tsx
  components/folder/NavBox.tsx
  components/layout/footer/Footer.tsx
  components/layout/header/Header.tsx
  components/layout/header/UserProfile.tsx
  components/sign/SignInputBox.styled.ts
  components/sign/SignInputBox.tsx
  components/sign/SignSns.styled.ts
  components/sign/SignSns.tsx
  constants/folderNav.ts
  constants/validationMsg.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/image/icon/eye-off.png
  public/image/icon/eye-on.png
  public/image/icon/icon-auth-kakao.png
  public/image/icon/icon_auth-google.png
  public/image/icon/icon_facebook copy.png
  public/image/icon/icon_instagram copy.png
  public/image/icon/icon_twitter copy.png
  public/image/icon/icon_youtube copy.png
  public/image/icon/main_logo copy.svg
  public/image/icon/sign_logo.svg
  styles/Global.styled.ts
  styles/pages/Sign.styled.ts
  types/Button.ts
  types/Sign.ts
  types/User.ts
  utills/copy.ts
  utills/validation.ts
Labels: 매운맛🔥

#434 [우제윤] Week14
  components/CardList/CardList.module.css
  components/CardList/CardList.tsx
  components/CardList/FolderItem.tsx
  components/FolderCardList.tsx
  components/FolderCardListItem.tsx
  components/FolderList.tsx
  components/FolderListMenu.tsx
  components/NavigationBar/NavProfile.tsx
  components/NavigationBar/NavigationBar.tsx
  components/Profile/Profile.tsx
  components/SearchBar/SearchBar.tsx
  lib/api/getUserFolder.ts
  lib/api/getUserInfo.ts
  lib/api/useFolderAsync.ts
  lib/api/useUserContext.ts
  lib/util/getClapsedTime.ts
  next.config.js
  package-lock.json
  package.json
Labels: 미완성🫠

#458 [김법균] Week14
  .eslintrc.json
  components/Account/Account.module.scss
  components/Account/Account.tsx
  components/FolderToolBar/FolderToolBar.module.scss
  components/FolderToolBar/FolderToolBar.tsx
  components/FolderToolBar/FolderToolBarButton.tsx
  components/FolderToolBar/UtilButton.tsx
  components/FolderToolBar/constants.ts
  components/Header/Header.tsx
  components/LinkCard/LinkCard.module.scss
  components/LinkCard/LinkCard.tsx
  components/LinkCardList/LinkCardList.module.scss
  components/LinkCardList/LinkCardList.tsx
  components/Modal/Modal.module.css
  components/Modal/Modal.tsx
  components/ModalContents/AddToFolderModal.tsx
  components/ModalContents/DeleteModal.tsx
  components/ModalContents/FolderInputModal.tsx
  components/ModalContents/ModalContents.module.scss
  components/ModalContents/ShareModal.tsx
  components/ModalContents/index.ts
  components/SearchBar/SearchBar.module.scss
  components/SearchBar/SearchBar.tsx
  components/ShowTextToggle/ShowTextToggle.module.scss
  components/ShowTextToggle/ShowTextToggle.tsx
  components/SignInForm/SignInForm.tsx
  components/SignUpForm/SignUpForm.tsx
  contexts/UserInfoContext.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  public/assets/images/add_icon.svg
  public/assets/images/add_icon_white.svg
  public/assets/images/check.svg
  public/assets/images/close.png
  public/assets/images/delete_icon.svg
  public/assets/images/delete_text.png
  public/assets/images/facebook.svg
  public/assets/images/kebab.svg
  public/assets/images/link.svg
  public/assets/images/no-image.png
  public/assets/images/pen_icon.svg
  public/assets/images/purplestar.svg
  public/assets/images/search_icon.svg
  public/assets/images/share_icon.svg
  public/assets/images/star.svg
  styles/AuthForm.module.scss
  styles/FolderPage.module.scss
  utils/axiosInstance.ts
  utils/interfaces.ts
  utils/shareFunctions/facebooShare.ts
  utils/shareFunctions/kakaoshare.ts
  utils/time-functions/formatDate.ts
  utils/time-functions/getTimeDifference.ts
Labels: 매운맛🔥, 미완성🫠

#466 [김은재] Week15
  api/folder.ts
  api/shared.ts
  api/user.ts
  components/common/Link.tsx
  components/common/modal/ModalLayout.styled.ts
  components/common/modal/modalContent/LinkAddContent.tsx
  components/common/modal/modalContent/ShareModalContent.tsx
  components/folder/NavBox.styled.tsx
  components/folder/NavBox.tsx
  components/folder/NavItem.styled.ts
  components/folder/NavItem.tsx
  components/layout/footer/Footer.tsx
  components/layout/header/Header.tsx
  components/layout/header/UserProfile.styled.ts
  components/layout/header/UserProfile.tsx
  components/shared/BookMark.tsx
  components/sign/SignInputBox.tsx
  constants/validationMsg.ts
  context/User.tsx
  hooks/useIsTokenRedirect.ts
  next.config.js
  pages/_app.tsx
  pages/folder/[[...navId]].tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  pages/shared/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/image/linkbrary.jpg
  public/image/main_link-download.png
  public/image/main_link-list.png
  public/image/main_link-name.png
  public/image/main_link-search.png
  public/image/main_link-share.png
  styles/Global.styled.ts
  styles/pages/Folder.styled.ts
  styles/pages/Main.styled.ts
  styles/pages/Shared.styled.ts
  styles/pages/Sign.styled.ts
  types/Button.ts
  types/Link.ts
  types/Sign.ts
  utills/copy.ts
Labels: 매운맛🔥

#479 [김현서] Week15
  weekly-mission/next-project/lib/api/authService.ts
  weekly-mission/next-project/lib/api/index.ts
  weekly-mission/next-project/next.config.mjs
  weekly-mission/next-project/pages/_app.tsx
  weekly-mission/next-project/pages/api/check-email.tsx
  weekly-mission/next-project/pages/api/sign-in.tsx
  weekly-mission/next-project/pages/api/sign-up.tsx
  weekly-mission/next-project/pages/folder/[folderId].tsx
  weekly-mission/next-project/pages/folder/index.tsx
  weekly-mission/next-project/pages/index.tsx
  weekly-mission/next-project/pages/service/fetchFolderLinksData.ts
  weekly-mission/next-project/pages/service/useFetchLink.ts
  weekly-mission/next-project/pages/service/useFolderData.ts
  weekly-mission/next-project/pages/service/useFolderList.tsx
  weekly-mission/next-project/pages/service/useFoldersByUserId.tsx
  weekly-mission/next-project/pages/service/useProfileData.tsx
  weekly-mission/next-project/pages/shared.tsx
  weekly-mission/next-project/pages/shared/[folderId].tsx
  weekly-mission/next-project/pages/signin.tsx
  weekly-mission/next-project/src/components/ActionButton/ActionButton.module.css
  weekly-mission/next-project/src/components/ActionButton/index.tsx
  weekly-mission/next-project/src/components/AllButton/index.tsx
  weekly-mission/next-project/src/components/Button/index.tsx
  weekly-mission/next-project/src/components/Card/index.tsx
  weekly-mission/next-project/src/components/CardList/index.tsx
  weekly-mission/next-project/src/components/Folder/index.tsx
  weekly-mission/next-project/src/components/FolderContent/LinksContent.tsx
  weekly-mission/next-project/src/components/FolderContent/index.tsx
  weekly-mission/next-project/src/components/FolderMenuList/index.tsx
  weekly-mission/next-project/src/components/Footer/FooterIcon.tsx
  weekly-mission/next-project/src/components/Header/index.tsx
  weekly-mission/next-project/src/components/Input/InputField.module.css
  weekly-mission/next-project/src/components/Layout/FolderPageLayout.tsx
  weekly-mission/next-project/src/components/Nav/Nav.module.css
  weekly-mission/next-project/src/components/Nav/index.tsx
  weekly-mission/next-project/src/context/FolderContext.tsx
  weekly-mission/next-project/styles/Home.module.css
  weekly-mission/next-project/styles/index.css
  weekly-mission/next-project/styles/sign.module.css
  weekly-mission/next-project/tsconfig.json
Labels: 미완성🫠

#474 [권주현] Week15
  api.ts
  common/Auth/Form/index.tsx
  common/Auth/Header/index.tsx
  common/Auth/Input/index.tsx
  common/Footer/index.module.css
  common/Header/index.tsx
  common/SearchBar/index.module.css
  common/SearchBar/index.tsx
  components/CardListPagesLayout/index.tsx
  components/EmptyLinkCards/index.module.css
  components/EmptyLinkCards/index.tsx
  components/FolderController/index.tsx
  components/FolderLinkCards/index.tsx
  components/FoldersList/index.module.css
  components/FoldersList/index.tsx
  components/LinkCard/index.module.css
  components/LinkCard/index.tsx
  components/LinkCards/index.module.css
  components/LinkCards/index.tsx
  components/LinkListPageLayout/index.tsx
  components/SharedLinkCard/index.tsx
  components/SharedLinkCards/index.tsx
  components/SocialAuthBox/index.tsx
  components/UserProfileAndTitle/index.tsx
  constants/index.ts
  hooks/api/useFolder.ts
  hooks/api/useLink.ts
  hooks/api/useUser.ts
  hooks/auth/useSignin.ts
  hooks/state/index.ts
  hooks/useAsync.ts
  hooks/useInitializeUser.ts
  hooks/useUserState.ts
  package-lock.json
  package.json
  pages/_app.page.tsx
  pages/folder/[folderId].page.tsx
  pages/folder/index.page.tsx
  pages/index.page.tsx
  pages/shared/[folderId].page.tsx
  pages/shared/index.page.tsx
  pages/signin/index.page.tsx
  pages/signup/index.page.tsx
  styles/LinkListPage.module.css
  styles/global.css
  types/api/index.ts
  types/folder/index.ts
  types/link/index.ts
  types/response/index.ts
  types/user/index.ts
Labels: 매운맛🔥

#472 [홍진호] week15
  app/(auth)/_components/footer.tsx
  app/(auth)/layout.tsx
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/page.tsx
  app/(route)/folder/[[...folder]]/_components/actionable-dropdown-menu.tsx
  app/(route)/folder/[[...folder]]/_components/add-folder-button.tsx
  app/(route)/folder/[[...folder]]/_components/category-button.tsx
  app/(route)/folder/[[...folder]]/_components/category-buttons.tsx
  app/(route)/folder/[[...folder]]/_components/control-buttons.tsx
  app/(route)/folder/[[...folder]]/_components/folder-card.tsx
  app/(route)/folder/[[...folder]]/_components/folder-cards.tsx
  app/(route)/folder/[[...folder]]/_components/hero.tsx
  app/(route)/folder/[[...folder]]/page.tsx
  app/(route)/folder/[id]/page.tsx
  app/(route)/folder/_components/category-buttons.tsx
  app/(route)/shared/page.tsx
  app/api/cookies.ts
  app/api/folder.ts
  app/api/links.ts
  app/api/user.ts
  app/layout.tsx
  bun.lockb
  lib/utils.ts
  next.config.mjs
  src/pages/folder/_components/actionable-dropdown-menu.tsx
Labels: 순한맛🐑

#471 [유호민] Week15
  axios/axiosInstance.ts
  component/FolderMain.tsx
  component/FolderTabs.tsx
  component/FolderTitlebar.tsx
  component/LinkCard.tsx
  component/LinkCardByFolderId.tsx
  component/LinkCardList.tsx
  component/Navbar.tsx
  component/SignHeader.tsx
  component/SigninForm.tsx
  component/SigninPasswordInput.tsx
  component/SignupForm.tsx
  component/SocialLogin.tsx
  lib/folderFetcher.ts
  lib/linkFetcher.ts
  lib/userFetcher.ts
  next.config.mjs
  pages/folder/[folderId].tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  pages/shared/index.tsx
Labels: 순한맛🐑

#476 [박상준] Week15
  .gitignore
  .vscode/settings.json
  @types/import-env.d.ts
  Portal.tsx
  api/api.ts
  components/Button/Button.styled.ts
  components/Card/Card.styled.ts
  components/Card/Card.tsx
  components/ContentsContainer.tsx
  components/FolderButton/FolderButton.tsx
  components/FolderButtonContainer/FolderButtonContainer.tsx
  components/FolderModalContainer/FolderModals.tsx
  components/Input/Input.styled.ts
  components/Input/Input.tsx
  components/KebabMenu/KebabMenu.styled.ts
  components/KebabMenu/KebabMenu.tsx
  components/Loading/Loading.styled.ts
  components/Loading/Loading.tsx
  components/MainSectionCard/MainSectionCard.styled.ts
  components/MainSectionCard/MainSectionCard.tsx
  components/Modal/AddFolderModal/AddFolderModal.tsx
  components/Modal/AddModal/AddModal.tsx
  components/Modal/BaseModal/BaseModal.styled.ts
  components/Modal/DeleteLinkModal/DeleteLinkModal.tsx
  components/Modal/DeleteModal/DeleteModal.styled.ts
  components/Modal/DeleteModal/DeleteModal.tsx
  components/Modal/EditModal/EditModal.tsx
  components/Modal/ShareModal/ShareModal.styled.ts
  components/Modal/ShareModal/ShareModal.tsx
  components/Nav/Nav.styled.ts
  components/Nav/Nav.tsx
  components/NotFound/NotFound.styled.ts
  components/NotFound/NotFound.tsx
  components/SearchBar/SearchBar.tsx
  components/Toast/Toast.styled.ts
  components/Toast/Toast.tsx
  hooks/useGetFolder.ts
  hooks/useGetFolderList.ts
  hooks/useGetUser.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder.tsx
  pages/folder/[[...folderId]].tsx
  pages/index.tsx
  pages/shared.tsx
  pages/shared/[[...folderId]].tsx
  pages/signin.tsx
  pages/signup.tsx
  public/LoadingIcon.svg
  styles/folder.styled.ts
  styles/index.styled.ts
  styles/reset.css
  styles/shared.styled.ts
  styles/signin.styled.ts
Labels: 매운맛🔥

#485 [Week15] 우지석
  api/config.js
  components/EmailInput.tsx
  components/Folder/AddLinkBar.tsx
  components/Folder/Button.tsx
  components/Folder/Card.tsx
  components/Folder/CardList.tsx
  components/Folder/FolderList.tsx
  components/Folder/Header.tsx
  components/Folder/Main.tsx
  components/Footer.tsx
  components/Header-Nav.tsx
  components/PasswordInput.tsx
  components/SearchBar.tsx
  components/Shared/Card.tsx
  components/Shared/Header-Content.tsx
  components/Shared/Main.tsx
  components/Shared/SharedHeader.tsx
  components/SignInForm.tsx
  components/SignUpForm.tsx
  components/SignUpPassword.tsx
  components/passwordToggle.js
  next.config.js
  package-lock.json
  package.json
  pages/_document.tsx
  pages/folder.tsx
  pages/folder/[[...folderId]].tsx
  pages/index.tsx
  pages/shared/[foderId].tsx
  pages/signin.tsx
  pages/signup.tsx
  public/icon/eye-off.svg
  public/icon/eye-on.svg
  public/icon/facebook.svg
  public/icon/google.svg
  public/icon/instagram.svg
  public/icon/kakao.svg
  public/icon/link.svg
  public/icon/search.svg
  public/icon/twitter.svg
  public/icon/youtube.svg
  public/img/Linkbrary.jpg
  public/img/main.png
  public/img/main.svg
  public/img/manage.png
  public/img/manage.svg
  public/img/meta.png
  public/img/save.png
  public/img/save.svg
  public/img/search.png
  public/img/search.svg
  public/img/share.png
  public/img/share.svg
  public/img/thumbnail.svg
  styles/index.module.scss
  styles/sign-in.module.scss
  styles/sign-up.module.scss
  utils/useFetch.ts
  utils/util.ts
Labels: 매운맛🔥, 미완성🫠

#482 [김법균] Week 15
  .eslintrc.json
  app/layout.tsx
  app/lib/definitions.ts
  app/shared/[folderId]/page.tsx
  app/shared/layout.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/Account/Account.tsx
  components/AddLinkBar/AddLinkBar.module.scss
  components/AddLinkBar/AddLinkBar.tsx
  components/AuthHeader/AuthHeader.tsx
  components/AuthHeader/AuthHeaderDescription.tsx
  components/AuthHeader/AuthHeaderLink.tsx
  components/Button/Button.tsx
  components/FolderPageContent/FolderPageContent.module.scss
  components/FolderPageContent/FolderPageContent.tsx
  components/FolderToolBar/FolderToolBar.module.scss
  components/FolderToolBar/FolderToolBar.tsx
  components/Footer/Footer.tsx
  components/Header/Header.tsx
  components/LinkCardList/LinkCardList.module.scss
  components/LinkCardList/LinkCardList.tsx
  components/ModalContents/ModalContents.module.scss
  components/ModalContents/ShareModal.tsx
  components/SearchBar/SearchBar.tsx
  components/SharedLinkCard/SharedLinkCard.tsx
  components/SharedLinkCardList/SharedLinkCardList.tsx
  components/SharedProfile/SharedProfile.module.scss
  components/SharedProfile/SharedProfile.tsx
  components/ShowTextToggle/ShowTextToggle.tsx
  components/SignInForm/SignInForm.tsx
  components/SignUpForm/SignUpForm.tsx
  contexts/AuthContext.tsx
  contexts/UserInfoContext.tsx
  hooks/useCurrentFolder.ts
  hooks/useFolders.ts
  hooks/useLinks.ts
  hooks/useModal.ts
  hooks/useSearchValue.ts
  hooks/useUserInfo.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder/[[...slug]].tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  styles/globals.css
  tsconfig.json
  utils/interfaces.ts
  utils/validateEmail.ts
Labels: 매운맛🔥
