Repository codeit-bootcamp-frontend/5-Weekly-Mission, pull requests merged in 2024-02, with the labels that each got.

#38 [김은재]Week2
  css/color.css
  css/index.css
  css/reset.css
  css/sign.css
  img/_img.png
  img/_img1.png
  img/_img4.png
  img/icon/Component 2.png
  img/icon/Component 3.png
  img/icon/akar-icons_facebook-fill.png
  img/icon/akar-icons_twitter-fill.png
  img/icon/akar-icons_youtube-fill.png
  img/icon/ant-design_instagram-filled.png
  img/icon/eye-off.png
  img/img2.png
  img/img3.png
  index.html
  member/signin.html
  member/signup.html
Labels: 매운맛🔥

#24 [김법균] week2
  week2/faq.html
  week2/img/Search.svg
  week2/img/_close.svg
  week2/img/_dim.png
  week2/img/akar-icons_facebook-fill.svg
  week2/img/akar-icons_twitter-fill.svg
  week2/img/akar-icons_youtube-fill.svg
  week2/img/ant-design_instagram-filled.svg
  week2/img/bg1.jpg
  week2/img/bg2.jpg
  week2/img/bg3.jpg
  week2/img/bg4.jpg
  week2/img/bg5.jpg
  week2/img/bg6.jpg
  week2/img/bg7.jpg
  week2/img/bg8.jpg
  week2/img/bg9.jpg
  week2/img/copylink.png
  week2/img/eye-off.svg
  week2/img/eye-on.svg
  week2/img/facebook.svg
  week2/img/google.svg
  week2/img/kakao.svg
  week2/img/kebab.svg
  week2/img/logo.svg
  week2/img/myprofile.svg
  week2/img/purplestar.svg
  week2/img/save.svg
  week2/img/share-bg-o.png
  week2/img/share-bg.png
  week2/img/share.svg
  week2/img/star-line-yellow-icon.svg
  week2/img/star.svg
  week2/index.html
  week2/privacy.html
  week2/signin.html
  week2/signup.html
  week2/style.css
Labels: 매운맛🔥

#35 [장재혁] week2
  part1-장재혁-week2/img/eye-off.svg
  part1-장재혁-week2/img/eye-on.svg
  part1-장재혁-week2/img/icons-google.svg
  part1-장재혁-week2/img/icons.cacaotalk.svg
  part1-장재혁-week2/img/icons.facebook.svg
  part1-장재혁-week2/img/icons.instagram.svg
  part1-장재혁-week2/img/icons.twitter.svg
  part1-장재혁-week2/img/icons.youtube.svg
  part1-장재혁-week2/img/img25.png
  part1-장재혁-week2/img/link-directory.svg
  part1-장재혁-week2/img/logo.svg
  part1-장재혁-week2/img/main_1.png
  part1-장재혁-week2/img/main_2.png
  part1-장재혁-week2/img/main_3.png
  part1-장재혁-week2/img/main_4.png
  part1-장재혁-week2/index.html
  part1-장재혁-week2/readme.md
  part1-장재혁-week2/signin.html
  part1-장재혁-week2/signup.html
  part1-장재혁-week2/style.css
Labels: 매운맛🔥

#16 [유호민]Week2
  weeklyMission1/css/style.css
  weeklyMission1/img/bookmark.svg
  weeklyMission1/img/card.png
  weeklyMission1/img/facebook.svg
  weeklyMission1/img/google.png
  weeklyMission1/img/hidden.svg
  weeklyMission1/img/img1.png
  weeklyMission1/img/img2.png
  weeklyMission1/img/img3-1.png
  weeklyMission1/img/img3.png
  weeklyMission1/img/img4.png
  weeklyMission1/img/instagram.svg
  weeklyMission1/img/kakao.svg
  weeklyMission1/img/logo-big.svg
  weeklyMission1/img/logo-small.svg
  weeklyMission1/img/search.svg
  weeklyMission1/img/small-circle-white.svg
  weeklyMission1/img/twitter.svg
  weeklyMission1/img/unhidden.svg
  weeklyMission1/img/youtube.svg
  weeklyMission1/index.html
  weeklyMission1/signin.html
  weeklyMission1/signup.html
Labels: 순한맛🐑

#23 [박준영]Week2
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
  static/css/signin.css
  static/css/signup.css
  static/css/style.css
  static/img/content2.png
  static/img/content3.png
  static/img/content4-1.png
  static/img/content4.png
  static/img/content5.png
  static/img/dim.png
  static/img/eyes.svg
  static/img/facebook.svg
  static/img/googleLogin.png
  static/img/instagram.svg
  static/img/kakaoLogin.png
  static/img/logo.svg
  static/img/twiter.svg
  static/img/youtube.svg
Labels: 매운맛🔥

#55 [임수혁] Week3
  .github/codeit.html
  .github/landing_img/downlodaicon.svg
  .github/landing_img/facebook_icon.svg
  .github/landing_img/instagram_icon.svg
  .github/landing_img/link.png
  .github/landing_img/login.png
  .github/landing_img/logo.png
  .github/landing_img/section_img1.png
  .github/landing_img/section_img2-1.png
  .github/landing_img/section_img2-2.png
  .github/landing_img/section_img3.png
  .github/landing_img/section_top_img1.png
  .github/landing_img/section_top_img2.png
  .github/landing_img/section_top_img3.png
  .github/landing_img/top_image.png
  .github/landing_img/twitter_icon.svg
  .github/landing_img/youtuber_icon.svg
  .github/landing_style.css
  .github/sign_img/signin-google2.png
  .github/sign_img/signin-googleback.svg
  .github/sign_img/signin-kakao.svg
  .github/sign_img/signin-kakaoback.svg
  .github/sign_img/signin.png
  .github/sign_img/signup.png
  .github/sign_style.css
  .github/signin.html
  .github/signup.html
Labels: 매운맛🔥, 미완성🫠

#31 [황은지] Week2
  CSS/common.css
  CSS/main.css
  CSS/sign.css
  Images/_img1.png
  Images/_img4.png
  Images/akar-icons_facebook-fill.svg
  Images/akar-icons_twitter-fill.svg
  Images/akar-icons_youtube-fill.svg
  Images/ant-design_instagram-filled.svg
  Images/eye-off.svg
  Images/icon-google.svg
  Images/icon-kakaotalk.svg
  Images/image25.png
  Images/img2.png
  Images/img3.png
  Images/logo.svg
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 순한맛🐑

#37 [박수민]week2
  facebook.svg
  faq.html
  images/Component 3.svg
  images/ac3d1341-2f3e-4385-a1ec-f2d007e1d3ee.txt
  images/google.png.png
  images/icon.ico
  images/kakao.png.png
  images/kakaotalk.svg
  images/landgin3.png
  images/landing1.png
  images/landing1_img.png
  images/landing2.png
  images/landing4.png
  images/landing4_back.png
  images/landing5.png
  images/landing_3.png
  index.html
  instagram.svg
  privacy.html
  signin.html
  signup.html
  style.css
  twitter.svg
  youtube.svg
Labels: 매운맛🔥

#41 [백승렬] Week 2
  weekly_mission/css/footer.css
  weekly_mission/css/index.css
  weekly_mission/css/landing-pc.css
  weekly_mission/css/login_signup.css
  weekly_mission/css/nav.css
  weekly_mission/footer.html
  weekly_mission/images/Linkbrary.svg
  weekly_mission/images/_img1_landing.svg
  weekly_mission/images/_img2_landing.svg
  weekly_mission/images/_img3_landing.svg
  weekly_mission/images/_img4_landing.svg
  weekly_mission/images/facebook_logo.png
  weekly_mission/images/facebook_logo.svg
  weekly_mission/images/google_logo.svg
  weekly_mission/images/image_25.png
  weekly_mission/images/instagram_logo.png
  weekly_mission/images/instagram_logo.svg
  weekly_mission/images/kakao_logo.svg
  weekly_mission/images/twitter_logo.png
  weekly_mission/images/twitter_logo.svg
  weekly_mission/images/youtube_logo.png
  weekly_mission/images/youtube_logo.svg
  weekly_mission/index.html
  weekly_mission/js/password-visible.js
  weekly_mission/login.html
  weekly_mission/nav.html
  weekly_mission/signup.html
Labels: 순한맛🐑

#45 [이유진]Week2
  Week2/css/indexStyle.css
  Week2/css/signinStyle.css
  Week2/css/signupStyle.css
  Week2/faq.html
  Week2/img/Component 2.svg
  Week2/img/Component 3.svg
  Week2/img/Linkbrary.svg
  Week2/img/_img.svg
  Week2/img/_img1.svg
  Week2/img/_img4.svg
  Week2/img/akar-icons_facebook-fill.svg
  Week2/img/akar-icons_twitter-fill.svg
  Week2/img/akar-icons_youtube-fill.svg
  Week2/img/ant-design_instagram-filled.svg
  Week2/img/img2.svg
  Week2/img/img3.svg
  Week2/index.html
  Week2/privacy.html
  Week2/signin.html
  Week2/signup.html
Labels: 순한맛🐑

#47 [김성범]Week2
  img/eye_on.svg
  img/facebook.svg
  img/google.svg
  img/image_box1.png
  img/image_box2.png
  img/image_box3.png
  img/image_box4.png
  img/image_box5.png
  img/instagram.svg
  img/kakao.svg
  img/logo.svg
  img/star.svg
  img/twitter.svg
  img/youtube.svg
  index.html
  login/login.css
  login/login.html
  signup/signup.css
  signup/signup.html
  style.css
Labels: 매운맛🔥

#17 [이순구]Week2
  Component 2.png
  Component 3.png
  Vector.png
  componets.css
  componets.html
  facebook.png
  faq.html
  img.png
  img1.png
  img2.png
  img3.png
  img4.png
  instragram.png
  lending.css
  lending.html
  logo.png
  privacy.html
  signin.css
  signin.html
  signup.css
  signup.html
  twitter.png
  youtube.png
Labels: 매운맛🔥

#59 [이상우]week2
  Card 1.svg
  Card-1.svg
  Card.svg
  Frame 2608782.svg
  content2.svg
  content3.svg
  content4.svg
  index.html
  logo.svg
  serch_logo.svg
  star.svg
  style.css
Labels: 미완성🫠, 순한맛🐑

#54 [이남경]Week2
  faq.html
  images/.DS_Store
  images/landing/_img.svg
  images/landing/_img1.svg
  images/landing/_img4.svg
  images/landing/akar-icons_facebook-fill.svg
  images/landing/akar-icons_twitter-fill.svg
  images/landing/akar-icons_youtube-fill.svg
  images/landing/ant-design_instagram-filled.svg
  images/landing/img2.svg
  images/landing/img3.svg
  images/signin/.DS_Store
  images/signin/Component 2.svg
  images/signin/Component 3.svg
  images/signin/logo.svg
  images/signup/Component 2.svg
  images/state=Default.png
  images/state=Selected.png
  index.html
  privacy.html
  signin.html
  signup.html
  style-signin.css
  style-signup.css
  style.css
Labels: 매운맛🔥

#36 [이주안]Week2
  faq.html
  img/Card3-back.png
  img/Card3.png
  img/Card4-img.png
  img/akar-icons_facebook-fill.svg
  img/akar-icons_twitter-fill.svg
  img/akar-icons_youtube-fill.svg
  img/ant-design_instagram-filled.svg
  img/card1.png
  img/card2.png
  img/eye-off.svg
  img/google.png
  img/googleback.svg
  img/header-logo.svg
  img/kakao.svg
  img/kakaoback.svg
  img/logo.svg
  img/mainbg.png
  index.html
  privacy.html
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#58 [김보민] Week2
  css/reset.css
  css/signin.css
  css/style.css
  images/99FE484C5C3451F218 1.svg
  images/Card 1.png
  images/Card-1.png
  images/Card.png
  images/Group 20.svg
  images/Kakao.svg
  images/akar-icons_facebook-fill.svg
  images/akar-icons_twitter-fill.svg
  images/akar-icons_youtube-fill.svg
  images/ant-design_instagram-filled.svg
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/google.svg
  images/image 25.png
  images/image25.png
  images/logo.svg
  images/스크린샷 2023-03-17 오후 3.22 1.png
  images/디스크립션 없는 팝업 1.png
  images/폴더 공유하기 팝업 1.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#19 [고학영] Week2
  part1/icons/99fe484c5c3451f218 1.svg
  part1/icons/akar-icons_facebook-fill.svg
  part1/icons/akar-icons_twitter-fill.svg
  part1/icons/akar-icons_youtube-fill.svg
  part1/icons/ant-design_instagram-filled.svg
  part1/icons/c3a9be9cb365010056fa7aa9cc9f05a2.png
  part1/icons/eye-on.svg
  part1/icons/facebook.svg
  part1/icons/google.svg
  part1/icons/group 20.svg
  part1/icons/logo.svg
  part1/images/_img.png
  part1/images/_img.svg
  part1/images/card1.png
  part1/images/card2.png
  part1/images/card3.png
  part1/images/folder_image.png
  part1/images/forder_share.png
  part1/images/screenshot.png
  part1/index.html
  part1/index_style.css
  part1/signin/signin.html
  part1/signin/signin_style.css
  part1/signup/signup.html
  part1/signup/signup_style.css
Labels: 매운맛🔥

#57 [조수연] Week2
  facebook.svg
  faq.html
  img1.png
  img2.png
  img3.png
  img4.png
  img5.png
  img6.png
  img7.png
  index.css
  index.html
  instagram.svg
  logo.svg
  privacy.html
  signin.css
  signin.html
  signup.html
  twitter.svg
  youtube.svg
Labels: 매운맛🔥

#28 [박상준]Week2
  css/signin.css
  css/style.css
  faq.html
  image/Card 1.png
  image/Card-1.png
  image/Card.png
  image/Group 20.svg
  image/akar-icons_facebook-fill.png
  image/akar-icons_twitter-fill.png
  image/akar-icons_youtube-fill.png
  image/ant-design_instagram-filled.png
  image/eye-off.svg
  image/facebook.svg
  image/google.svg
  image/image 25.png
  image/logo.svg
  image/logo_google.png
  image/logo_kakao.svg
  image/디스크립션 없는 팝업 1.png
  image/스크린샷 2023-03-17 오후 3.22 1.png
  image/폴더 공유하기 팝업 1.png
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#46 [오다은]Week2
  css/default.css
  css/main.css
  css/signin.css
  img/eye_off.png
  img/eye_on.png
  img/login_google.png
  img/login_kakaotalk.png
  img/logo.png
  img/logo_big.png
  img/main_bg.png
  img/section1.png
  img/section2.png
  img/section3.png
  img/section4.png
  img/sns_facebook.png
  img/sns_instagram.png
  img/sns_twitter.png
  img/sns_youtube.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#43 [장문원]week2
  .DS_Store
  fonts/Acme-Regular.ttf
  img/contents-01.png
  img/contents-02.png
  img/contents-03.png
  img/contents-04.png
  img/footer/facebook.svg
  img/footer/instagram.svg
  img/footer/twitter.svg
  img/footer/youtube.svg
  img/header.png
  img/logo.svg
  img/signin/eye-off.svg
  img/signin/google.png
  img/signin/kakao.png
  img/signin/signin-logo.svg
  index.html
  signin.html
  signup.html
  styles/.DS_Store
  styles/color.css
  styles/global.css
  styles/index.css
  styles/reset.css
  styles/singin-up.css
Labels: 매운맛🔥

#40 [정지성] Week2
  .github/Group 20.png
  .github/Linkbrary-logo.svg
  .github/content2.png
  .github/content3.png
  .github/content4.png
  .github/content5.png
  .github/eye-off.svg
  .github/eye-on.svg
  .github/facebook.svg
  .github/faq.html
  .github/googlelogo.png
  .github/image 25.png
  .github/index.html
  .github/instagram.svg
  .github/kakaologo.png
  .github/privacy.html
  .github/signin.html
  .github/signup.html
  .github/style.css
  .github/style2.css
  .github/style3.css
  .github/twitter.svg
  .github/youtube.svg
Labels: 순한맛🐑

#1 [장성훈] Week2
  img/Linkbrary.png
  img/footer/Vector-1.png
  img/footer/Vector-2.png
  img/footer/Vector-3.png
  img/footer/Vector-4.png
  img/landing/img_1.png
  img/landing/img_2.png
  img/landing/img_3.png
  img/landing/img_4.png
  img/landing/img_5.png
  img/socialLogin/google_logo.png
  img/socialLogin/kakao_logo.png
  index.html
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#61 [정성혜] Week2
  week2/css/color.css
  week2/css/font.css
  week2/css/landing.css
  week2/css/signin.css
  week2/css/signup.css
  week2/main.html
  week2/signin.html
  week2/signup.html
  week2/src/Linkbrary.png
  week2/src/add_link.svg
  week2/src/codeit_2023.png
  week2/src/content1.png
  week2/src/content2.png
  week2/src/content3.png
  week2/src/content4.png
  week2/src/content5.png
  week2/src/facebook.png
  week2/src/google.png
  week2/src/insta.png
  week2/src/login.svg
  week2/src/policy_faq.png
  week2/src/signin.png
  week2/src/twitter.png
  week2/src/youtube.png
Labels: 미완성🫠

#29 [Week2]배의진
  faq/Faq.html
  images/eye-off.png
  images/eye-off.svg
  images/eye-on.png
  images/eye-on.svg
  images/icon_facebook.svg
  images/icon_google.svg
  images/icon_instagram.svg
  images/icon_kakao.svg
  images/icon_twitter.svg
  images/icon_youtube.svg
  images/img-main.png
  images/img-main.svg
  images/img1.png
  images/img1.svg
  images/img2.png
  images/img2.svg
  images/img3.png
  images/img3.svg
  images/img4.png
  images/img4.svg
  images/logo.png
  images/logo.svg
  images/sns_facebook.png
  images/sns_instagram.png
  images/sns_twitter.png
  images/sns_youtube.png
  privacy/Privacy.html
  signin/style-로그인.css
  signin/로그인.html
  signup/style-회원가입.css
  signup/회원가입.html
  style-랜딩.css
  style.css
  랜딩.html
Labels: 매운맛🔥

#33 [김다진]Week2
  .github/pull_request_template.md
  fap.html
  footer.css
  header.css
  icon/Sociallogin-google.png
  icon/Sociallogin-kakao.png
  icon/akar-icons_facebook-fill.png
  icon/akar-icons_twitter-fill.png
  icon/akar-icons_youtube-fill.png
  icon/ant-design_instagram-filled.png
  icon/eye-off.svg
  icon/icon-link.png
  icon/logo-facebook.png
  icon/logo-kakao.png
  img-landing/img.png
  img-landing/img1.png
  img-landing/img2.png
  img-landing/img3.png
  img-landing/img4.png
  img-landing/logo.svg
  index.html
  landing.css
  privacy.html
  pull_request_template.md
  reset.css
  screenshot/screenshot-landing.png
  screenshot/screenshot-signin.png
  screenshot/screenshot-signup.png
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#39 [김현서] Week2
  Linkbrary.png
  Vector.jpg
  card1.png
  card2.png
  card3.png
  google icon.png
  image25.png
  index.html
  kakao icon.png
  mainstyle.css
  signin.html
  signinstyle.css
  signup.html
  signupstyle.css
  디스크립션없는팝업.png
  스크린샷.png
  폴더 공유하기.png
Labels: 순한맛🐑

#13 [우제윤] Week2
  css/indexStyle.css
  css/login.css
  css/signup.css
  faq.html
  img/Vector.png
  img/bed.png
  img/dog.png
  img/fav.png
  img/gra.png
  img/icn_facebook.png
  img/icn_goolge.png
  img/icn_instagram.png
  img/icn_kakao.png
  img/icn_twitter.png
  img/icn_youtube.png
  img/landing/Card 1.png
  img/landing/Card-1.png
  img/landing/Card.png
  img/landing/image 25.png
  img/landing/디스크립션 없는 팝업 1.png
  img/landing/스크린샷 2023-03-17 오후 3.22 1.png
  img/landing/폴더 공유하기 팝업 1.png
  img/page.png
  img/page2.png
  img/search.png
  img/share.png
  index.html
  login.html
  privacy.html
  signup.html
  첫플랜.jpg
Labels: 순한맛🐑

#65 [임상훈]Week2
  index.html
  main_stylesheet.css
  pictures/.DS_Store
  pictures/1.png
  pictures/2.png
  pictures/3.png
  pictures/4.png
  pictures/5.png
  pictures/Linkbrary.png
  pictures/facebook.png
  pictures/google_logo.png
  pictures/instagram.png
  pictures/kakao_logo.png
  pictures/twitter.png
  pictures/youtube.png
  sign_in.css
  sign_in.html
  signup.css
  signup.html
Labels: 매운맛🔥

#73 [김한샘]Week3
  css/font.css
  css/form.css
  css/pages/login/login.css
  css/pages/login/mediaquery.css
  css/pages/main/main.css
  css/pages/main/mediaquery.css
  html/signin.html
  html/signup.html
  images/cat.jpg
  images/icon/svg/akar-icons_facebook-fill.svg
  images/icon/svg/akar-icons_twitter-fill.svg
  images/icon/svg/akar-icons_youtube-fill.svg
  images/icon/svg/ant-design_instagram-filled.svg
  images/svg/Linkbrary.svg
  index.html
  js/common.js
Labels: 매운맛🔥

#51 [우지석]Week2
  img/facebook.svg
  img/google.svg
  img/instagram.svg
  img/kakao.svg
  img/logo.svg
  img/main.png
  img/manage.png
  img/save.png
  img/search.png
  img/share.png
  img/twitter.svg
  img/youtube.svg
  main.html
  main.style.css
  signUp.css
  signin.css
  signin.html
  signup.html
Labels: 순한맛🐑
