Repository codeit-bootcamp-frontend/5-Weekly-Mission, pull requests merged in 2024-04, with the labels that each got.

#306 [김나연] Week7
  package-lock.json
  package.json
  public/images/card-default.png
  public/images/facebook.svg
  public/images/instagram.svg
  public/images/linkbrary.svg
  public/images/search.svg
  public/images/twitter.svg
  public/images/youtube.svg
  src/App.js
  src/color.css
  src/components/hook/fetchDataHook.jsx
  src/components/section/CardData/CardData.css
  src/components/section/CardData/CardData.jsx
  src/components/section/FolderInfo/FolderInfo.css
  src/components/section/FolderInfo/FolderInfo.jsx
  src/components/section/Footer/Footer.css
  src/components/section/Footer/Footer.jsx
  src/components/section/MainContent/MainContent.css
  src/components/section/MainContent/MainContent.jsx
  src/components/section/NavigationBar/NavigationBar.css
  src/components/section/NavigationBar/NavigationBar.jsx
  src/components/section/SearchBar/SearchBar.css
  src/components/section/SearchBar/SearchBar.jsx
  src/components/util/GetApi.jsx
  src/components/util/TimeAgo.js
  src/global.css
  src/reset.css
Labels: 매운맛🔥

#293 [이주안]Week7
  package-lock.json
  package.json
  public/index.html
  src/PageLink.js
  src/api/AppApi.js
  src/assets/SearchIcon.svg
  src/assets/facebookIcon.svg
  src/assets/instagramIcon.svg
  src/assets/logo.svg
  src/assets/noImage.svg
  src/assets/twitterIcon.svg
  src/assets/youtubeIcon.svg
  src/components/App.js
  src/components/Button.js
  src/components/Cards.js
  src/components/Footer.js
  src/components/MainProfile.js
  src/components/Navigation.js
  src/components/Search.js
  src/components/User.js
  src/index.js
  src/pages/Signin.js
Labels: 매운맛🔥, 미완성🫠

#307 [장문원] week7
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/Search.svg
  src/assets/facebook.svg
  src/assets/instagram.svg
  src/assets/logo.svg
  src/assets/noImageLogo.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/Card.css
  src/components/Card.jsx
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/SearchBar.css
  src/components/User.css
  src/components/User.jsx
  src/hooks/useFetchFolder.jsx
  src/hooks/useFetchUser.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/FolderListPage.css
  src/pages/FolderListPage.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#278 [이진욱] Week7
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Main.js
  src/api/index.js
  src/assets/icons/account.svg
  src/assets/icons/blank_logo.svg
  src/assets/icons/eye-off.svg
  src/assets/icons/eye-on.svg
  src/assets/icons/fill_facebook_icon.svg
  src/assets/icons/fill_instagram_icon.svg
  src/assets/icons/fill_twitter_icon.svg
  src/assets/icons/fill_youtube_icon.svg
  src/assets/icons/google_icon.svg
  src/assets/icons/kakao_icon.svg
  src/assets/icons/logo.svg
  src/assets/icons/search.svg
  src/assets/icons/state=Default.svg
  src/assets/icons/state=Selected.svg
  src/assets/images/main_folder.png
  src/assets/images/main_header.png
  src/assets/images/main_link.png
  src/assets/images/main_share.png
  src/assets/images/main_sns.png
  src/components/App.js
  src/components/Card.css
  src/components/Card.js
  src/components/FolderOwner.css
  src/components/FolderOwner.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Nav.css
  src/components/Nav.js
  src/components/Search.css
  src/components/Search.js
  src/hooks/useAsync.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/FolderPage.css
  src/pages/FolderPage.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/colors.css
  src/styles/reset.css
  src/utils/CalculatorTime.js
  src/utils/IsUserLoggedIn.js
Labels: 매운맛🔥

#263 [홍진호] week7
  .eslintrc.cjs
  .gitignore
  README.md
  components.json
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/facebook.png
  public/favicon.ico
  public/index.html
  public/insta.png
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  public/twitter.png
  public/vite.svg
  public/youtube.png
  src/App.css
  src/App.js
  src/App.test.js
  src/App.tsx
  src/components/card.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/skeleton.tsx
  src/components/user-button.tsx
  src/data/get-folder-data.ts
  src/data/get-user-data.ts
  src/index.css
  src/index.js
  src/lib/date.ts
  src/lib/utils.ts
  src/logo.svg
  src/main.tsx
  src/pages/error/page.tsx
  src/pages/home/_components/footer.tsx
  src/pages/home/_components/navbar.tsx
  src/pages/home/_components/search-bar.tsx
  src/pages/home/layout.tsx
  src/pages/home/page.tsx
  src/pages/link/page.tsx
  src/reportWebVitals.js
  src/setupTests.js
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 순한맛🐑

#296 [박수민] week7
  package-lock.json
  package.json
  public/favicon.ico
  public/index.css
  public/index.html
  public/logo192.png
  public/logo512.png
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/HomePage.js
  src/assets/NoImage.svg
  src/assets/Search.svg
  src/assets/facebook.svg
  src/assets/icon.ico
  src/assets/instagram.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/cardlist.css
  src/components/cardlist.jsx
  src/components/foldertitle.css
  src/components/foldertitle.jsx
  src/components/footer.css
  src/components/footer.jsx
  src/components/header.css
  src/components/header.jsx
  src/components/mainsection.css
  src/components/mainsection.jsx
  src/components/profile.css
  src/components/profile.jsx
  src/components/searchbar.css
  src/components/searchbar.jsx
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/usefetch.js
Labels: 매운맛🔥

#309 [정성혜] Week7
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/icon/eye-off.png
  src/assets/icon/eye-on.png
  src/assets/icon/google.png
  src/assets/icon/kakao.png
  src/assets/icon/search.png
  src/assets/images/card-default.png
  src/assets/images/profile.png
  src/assets/svg/Linkbrary.svg
  src/assets/svg/akar-icons_facebook-fill.svg
  src/assets/svg/akar-icons_twitter-fill.svg
  src/assets/svg/akar-icons_youtube-fill.svg
  src/assets/svg/ant-design_instagram-filled.svg
  src/assets/variable.css
  src/components/CardList.css
  src/components/CardList.js
  src/components/ContentWrap.css
  src/components/ContentWrap.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Navigator.css
  src/components/Navigator.js
  src/components/SearchInput.css
  src/components/SearchInput.js
  src/global.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/reset.css
  src/setupTests.js
  src/styles/color.css
  src/styles/font.css
  src/styles/form.css
  src/utils/calculateTimeDiff.js
  src/utils/formatDate.js
Labels: 미완성🫠

#254 [우제윤] Week6
  .vscode/settings.json
  js/accessToken.js
  login/index.js
  login/tags.js
Labels: 순한맛🐑

#265 [장재혁] week6
  part1-장재혁-week6/faq.html
  part1-장재혁-week6/folder.html
  part1-장재혁-week6/images/eye-off.svg
  part1-장재혁-week6/images/eye-on.svg
  part1-장재혁-week6/images/facebook.svg
  part1-장재혁-week6/images/google.png
  part1-장재혁-week6/images/hero.png
  part1-장재혁-week6/images/image1.png
  part1-장재혁-week6/images/image2.png
  part1-장재혁-week6/images/image3.png
  part1-장재혁-week6/images/image4.png
  part1-장재혁-week6/images/instagram.svg
  part1-장재혁-week6/images/kakao.svg
  part1-장재혁-week6/images/logo.svg
  part1-장재혁-week6/images/twitter.svg
  part1-장재혁-week6/images/youtube.svg
  part1-장재혁-week6/index.html
  part1-장재혁-week6/privacy.html
  part1-장재혁-week6/signin.html
  part1-장재혁-week6/signup.html
  part1-장재혁-week6/src/colors.css
  part1-장재혁-week6/src/global.css
  part1-장재혁-week6/src/landing.css
  part1-장재혁-week6/src/reset.css
  part1-장재혁-week6/src/sign.css
  part1-장재혁-week6/src/signin.js
  part1-장재혁-week6/src/signup.js
  part1-장재혁-week6/src/utils.js
Labels: 매운맛🔥

#271 [이유진]Week6
  Weekly-Mission/css/sign.css
  Weekly-Mission/scripts/sign-in.js
  Weekly-Mission/scripts/sign-up.js
  Weekly-Mission/scripts/signin.js
  Weekly-Mission/scripts/signup.js
  Weekly-Mission/scripts/utils.js
  Weekly-Mission/signin.html
  Weekly-Mission/signup.html
Labels: 순한맛🐑

#282 [김현서] Week7
  image/Linkbrary.png
  image/Linkbrary.svg
  image/Screenshot_landing.png
  image/Vector.jpg
  image/card.jpg
  image/dim.jpg
  image/eye-off.jpg
  image/eye-on.jpg
  image/google icon.png
  image/image25.png
  image/img3.png
  image/kakao icon.png
  image/디스크립션 없는 팝업.jpg
  image/스크린샷.jpg
  image/폴더 공유하기.png
  index.css
  index.html
  signin/folder.html
  signin/sign.css
  signin/signin.html
  signin/signin.js
  signup/signup.html
  styles/color.css
  styles/common.css
  styles/ui.css
  weekly-mission/.eslintrc.cjs
  weekly-mission/.gitignore
  weekly-mission/README.md
  weekly-mission/image/Linkbrary.png
  weekly-mission/image/Search.png
  weekly-mission/image/dim.jpg
  weekly-mission/image/noimage.svg
  weekly-mission/image/profile img.jpg
  weekly-mission/index.html
  weekly-mission/package-lock.json
  weekly-mission/package.json
  weekly-mission/src/App.jsx
  weekly-mission/src/Hooks/useFetchData.jsx
  weekly-mission/src/components/Card.jsx
  weekly-mission/src/components/Cards.jsx
  weekly-mission/src/components/Footer.jsx
  weekly-mission/src/components/FooterIcon.jsx
  weekly-mission/src/components/Header.jsx
  weekly-mission/src/components/Main.jsx
  weekly-mission/src/components/Nav.jsx
  weekly-mission/src/components/Searchbar.jsx
  weekly-mission/src/main.jsx
  weekly-mission/src/pages/LinkSharePage.jsx
  weekly-mission/vite.config.js
Labels: 순한맛🐑

#288 [전유민] week7
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/Components/Card.js
  src/Components/Header.js
  src/Components/Main.js
  src/Components/Profile.js
  src/Components/SearchBar.js
  src/Shared.js
  src/api/user.js
  src/hooks/useFetch.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/static/css/common.css
  src/static/css/font.css
  src/static/css/main.css
  src/static/css/reset.css
  src/static/images/image.png
  src/static/images/logo.svg
  src/static/images/search.svg
Labels: 매운맛🔥

#279 [최준엽] Week7
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/defaultImage.svg
  src/assets/logo.svg
  src/assets/search.svg
  src/assets/snslogo/facebook.svg
  src/assets/snslogo/instagram.svg
  src/assets/snslogo/kakao.svg
  src/assets/snslogo/twitter.svg
  src/assets/snslogo/youtube.svg
  src/components/Card.jsx
  src/components/Content.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Nav.jsx
  src/components/Search.jsx
  src/components/apis/GetApi.jsx
  src/components/hooks/useFetch.jsx
  src/components/utils/CardUtil.jsx
  src/index.css
  src/main.jsx
  src/styles/CardStyled.jsx
  src/styles/Color.css
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Nav.css
  src/styles/SearchStyled.jsx
  vite.config.js
  yarn.lock
Labels: 매운맛🔥

#290 [우지석] Week7
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/CSS/global.css
  src/CSS/reset.css
  src/Components/Card.js
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/Main.js
  src/Pages/HomePage.js
  src/api.js
  src/images/Linkbrary.svg
  src/images/SearchIcon.svg
  src/images/facebook.svg
  src/images/instagram.svg
  src/images/thumbnail.svg
  src/images/twitter.svg
  src/images/youtube.svg
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/useFetch.js
Labels: 매운맛🔥

#310 Part2 조수연
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/color.css
  src/contents/Footer/Footer.css
  src/contents/Footer/Footer.js
  src/contents/Head/Head.css
  src/contents/Head/Head.js
  src/contents/Main/Main.css
  src/contents/Main/Main.js
  src/contents/NavigationBar/NavigationBar.css
  src/contents/NavigationBar/NavigationBar.js
  src/global.css
  src/hooks/useFetch.js
  src/images/blankImage.svg
  src/images/facebook.svg
  src/images/instagram.svg
  src/images/linkbrary.svg
  src/images/profile.svg
  src/images/search.svg
  src/images/twitter.svg
  src/images/youtube.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/reset.css
  src/setupTests.js
Labels: 매운맛🔥, 미완성🫠

#286 [김한샘] Week7
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/icon/Search.png
  src/assets/icon/eye-off.png
  src/assets/icon/eye-on.png
  src/assets/icon/google.png
  src/assets/icon/kakao.png
  src/assets/icon/svg/akar-icons_facebook-fill.svg
  src/assets/icon/svg/akar-icons_twitter-fill.svg
  src/assets/icon/svg/akar-icons_youtube-fill.svg
  src/assets/icon/svg/ant-design_instagram-filled.svg
  src/assets/images/cat.jpg
  src/assets/svg/Linkbrary.svg
  src/components/Card.css
  src/components/Card.jsx
  src/components/CardList.css
  src/components/CardList.jsx
  src/components/ConHeader.css
  src/components/ConHeader.jsx
  src/components/ContentWrap.css
  src/components/ContentWrap.jsx
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/Profile.css
  src/components/Profile.jsx
  src/components/Search.css
  src/components/Search.jsx
  src/fetchUtils/index.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/color.css
  src/styles/font.css
  src/styles/form.css
  src/styles/pages/login/login.css
  src/styles/pages/main/main.css
  src/styles/reset.css
  src/styles/zIndex.css
  src/utils/GetDate.jsx
  src/utils/GetDaysAgo.jsx
Labels: 매운맛🔥

#299 [권주현] Week7
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/Linkbrary.png
  src/assets/error.png
  src/components/Avatar.js
  src/components/Avatar.module.css
  src/components/FavoriteLinkCard.js
  src/components/FavoriteLinkCard.module.css
  src/components/FavoriteLinkCards.js
  src/components/FavoriteLinkCards.module.css
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/GlobalNavigationBar.js
  src/components/GlobalNavigationBar.module.css
  src/components/SearchBar.js
  src/components/SearchBar.module.css
  src/components/UserProfileAndTitle.js
  src/components/UserProfileAndTitle.module.css
  src/global.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/services/api.js
  src/setupTests.js
  src/utils/dateUtils.js
Labels: 매운맛🔥

#269 [이상우] week6
  index.js
  signin.html
  signup.js
Labels: 매운맛🔥, 미완성🫠

#302 [장재혁] Week7
  package-lock.json
  package.json
  public/favicon.ico
  public/images/eye-off.svg
  public/images/eye-on.svg
  public/images/facebook.svg
  public/images/google.png
  public/images/hero.png
  public/images/image1.png
  public/images/image2.png
  public/images/image3.png
  public/images/image4.png
  public/images/instagram.svg
  public/images/kakao.svg
  public/images/logo.svg
  public/images/search.svg
  public/images/twitter.svg
  public/images/youtube.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Account.js
  src/components/Body.js
  src/components/Card.js
  src/components/CardList.js
  src/components/Cta.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Nav.js
  src/components/SearchBar.js
  src/contexts/UserContext.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/colors.css
  src/utils/fetchSampleFolder.js
  src/utils/fetchUserData.js
  src/utils/formatDate.js
  src/utils/reset.css
Labels: 매운맛🔥, 미완성🫠

#339 [이남경] Week8
  eslint.config.mjs
  package-lock.json
  package.json
  src/Main.js
  src/api/index.js
  src/assets/deleteicon.svg
  src/assets/icon_share.svg
  src/assets/kebab.svg
  src/assets/penicon.svg
  src/assets/plus.svg
  src/assets/plus_white.svg
  src/assets/shareicon.svg
  src/assets/star__state=Default.svg
  src/assets/star__state=Selected.svg
  src/components/AddLink.module.css
  src/components/Button.js
  src/components/DeleteButton.js
  src/components/EditButton.module.css
  src/components/EditNameButton.js
  src/components/FixedActionButton.js
  src/components/FixedActionButton.module.css
  src/components/FloatingActionButton.js
  src/components/FloatingActionButton.module.css
  src/components/FolderButton.js
  src/components/FolderButton.module.css
  src/components/FolderButtonList.js
  src/components/FolderButtonList.module.css
  src/components/Footer.module.css
  src/components/LinkItem.js
  src/components/LinkItem.module.css
  src/components/Nav.js
  src/components/SearchBar.js
  src/components/ShareButton.js
  src/components/Warn.js
  src/components/Warn.module.css
  src/pages/Favorite.module.css
  src/pages/FavoriteListPage.js
  src/pages/FolderPage.js
  src/pages/FolderPage.module.css
Labels: 매운맛🔥

#327 [김현서] Week8
  weekly-mission/.eslintrc.cjs
  weekly-mission/.gitignore
  weekly-mission/image/delete.png
  weekly-mission/image/link.png
  weekly-mission/image/pen.png
  weekly-mission/image/profileimg.jpg
  weekly-mission/image/share.png
  weekly-mission/package-lock.json
  weekly-mission/package.json
  weekly-mission/src/App.jsx
  weekly-mission/src/Hooks/useFetchData.jsx
  weekly-mission/src/components/Main.jsx
  weekly-mission/src/components/Searchbar.jsx
  weekly-mission/src/components/folderpage/FolderContent.jsx
  weekly-mission/src/components/folderpage/FolderLayout.jsx
  weekly-mission/src/components/folderpage/FolderLists.jsx
  weekly-mission/src/components/folderpage/Foldermenu.jsx
  weekly-mission/src/components/folderpage/LinksContent.jsx
  weekly-mission/src/components/folderpage/NoLinks.jsx
  weekly-mission/src/components/folderpage/buttons/ActionButtons.jsx
  weekly-mission/src/components/folderpage/buttons/AddButton.jsx
  weekly-mission/src/components/folderpage/buttons/AllButton.jsx
  weekly-mission/src/components/folderpage/buttons/DeleteButton.jsx
  weekly-mission/src/components/folderpage/buttons/RenameButton.jsx
  weekly-mission/src/components/folderpage/buttons/ShareButton.jsx
  weekly-mission/src/components/folderpage/header/AddFolderLink.jsx
  weekly-mission/src/components/folderpage/header/AddLinkSection.jsx
  weekly-mission/src/components/linksharepage/Card.jsx
  weekly-mission/src/components/linksharepage/Cards.jsx
  weekly-mission/src/components/linksharepage/Header.jsx
  weekly-mission/src/components/linksharepage/SearchAndCards.jsx
  weekly-mission/src/components/shared/Button.jsx
  weekly-mission/src/components/shared/Footer.jsx
  weekly-mission/src/components/shared/FooterIcon.jsx
  weekly-mission/src/components/shared/Nav.jsx
  weekly-mission/src/components/shared/Searchbar.jsx
  weekly-mission/src/pages/FolderPage.jsx
  weekly-mission/src/pages/HomePage.jsx
  weekly-mission/src/pages/LinkSharePage.jsx
  weekly-mission/src/utils/FetchFolderLinksData.jsx
  weekly-mission/src/utils/Function.jsx
  weekly-mission/vite.config.js
Labels: 미완성🫠, 순한맛🐑

#314 [홍진호] week8
  package-lock.json
  package.json
  src/App.tsx
  src/components/card-wrapper.tsx
  src/components/feed-wrapper.tsx
  src/components/footer.tsx
  src/components/hero-warpper.tsx
  src/components/navbar.tsx
  src/components/search-bar.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/sonner.tsx
  src/components/user-button.tsx
  src/components/user-icon.tsx
  src/data/folders.ts
  src/data/get-user-data.ts
  src/data/users.ts
  src/lib/api.ts
  src/main.tsx
  src/pages/error/page.tsx
  src/pages/folder/_components/action-button-group.tsx
  src/pages/folder/_components/folder-card.tsx
  src/pages/folder/_components/link-category-button.tsx
  src/pages/folder/_components/link-search-bar.tsx
  src/pages/folder/page.tsx
  src/pages/home/layout.tsx
  src/pages/home/page.tsx
  src/pages/link-detail/page.tsx
  src/pages/shared/_components/link-card-list.tsx
  src/pages/shared/_components/shard-card.tsx
  src/pages/shared/_components/user-account-nav.tsx
  src/pages/shared/page.tsx
Labels: 순한맛🐑

#319 [김미소]Week8
  .vscode/settings.json
  public/assets/icon/icon_gray_delete.svg
  public/assets/icon/icon_gray_pen.svg
  public/assets/icon/icon_gray_share.svg
  public/assets/icon/icon_primary_add.svg
  public/assets/icon/icon_primaty_link.svg
  public/assets/icon/icon_star_off.svg
  public/assets/icon/icon_white_add.svg
  public/dummy.json
  src/components/common/Header.tsx
  src/components/common/atoms/Button.tsx
  src/components/common/atoms/Input.tsx
  src/components/common/atoms/LinkButton.tsx
  src/components/common/atoms/LinkButtonStyle.ts
  src/components/common/atoms/buttonStyle.ts
  src/components/common/atoms/inputStyle.ts
  src/components/common/headerStyle.ts
  src/components/common/interface.ts
  src/components/folder/PostCard.tsx
  src/components/folder/PostCardStyle.ts
  src/components/form/FormInput.tsx
  src/components/form/InputStyle.ts
  src/constant/api.ts
  src/hook/useFetch.tsx
  src/pages/Index.tsx
  src/pages/error/NotFoundPage.tsx
  src/pages/faq/Index.tsx
  src/pages/folder/Index.tsx
  src/pages/folder/Shared.tsx
  src/pages/folder/folderStyle.ts
  src/pages/folder/interface.ts
  src/pages/policy/Index.tsx
  src/router.tsx
  src/styles/commonStyle.ts
  src/styles/globalStyle.ts
  src/utils/calcTilmAgo.ts
Labels: 매운맛🔥

#315 [이현승] week 8
  WeeklyMissionPart1/Api.js
  package-lock.json
  package.json
  src/Hooks/useData.js
  src/Main.js
  src/asset/Star 1.png
  src/asset/add.svg
  src/asset/addWhite.svg
  src/asset/delete.svg
  src/asset/kebab.png
  src/asset/linkIcon.svg
  src/asset/pen.svg
  src/asset/share.svg
  src/asset/star.svg
  src/components/AddLink.js
  src/components/Api.js
  src/components/App.js
  src/components/Card.js
  src/components/CardList.js
  src/components/Favorite.js
  src/components/FolderPage/Folder.js
  src/components/FolderPage/FolderBar.js
  src/components/FolderPage/FolderContents.js
  src/components/FolderPage/FolderNameBar.js
  src/components/Footer.js
  src/components/GlobalStyle.js
  src/components/Header.js
  src/components/MainContent.js
  src/components/SearchBar.js
  src/components/SharedPage/Shared.js
  src/components/SharedPage/UserFolderInfo.js
  src/components/SubHeader.js
  src/components/Top.js
  src/index.js
  src/pages/FolderPage.js
  src/pages/SharedPage.js
Labels: 순한맛🐑

#324 Part2 박수민 week8
  src/HomePage.js
  src/assets/add.svg
  src/assets/delete.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/components/cardlist.css
  src/components/cardlist.jsx
  src/components/etcicon.jsx
  src/components/etcicon.module.css
  src/components/folderlist.jsx
  src/components/folderlist.module.css
  src/components/foldermain.jsx
  src/components/foldermain.module.css
  src/components/folderpluslink.jsx
  src/components/folderpluslink.module.css
  src/components/footer.css
  src/components/header.css
  src/components/mainsection.jsx
  src/folder.css
  src/folder.js
Labels: 매운맛🔥

#317 Part2 정지성 week8
  src/assets/addfolder.svg
  src/assets/changenameicon.svg
  src/assets/deleteicon.svg
  src/assets/link.svg
  src/assets/moreoptionicon.svg
  src/assets/shareicon.svg
  src/assets/staricon.svg
  src/components/Addlink/index.jsx
  src/components/Addlink/index.module.css
  src/components/Article/Article.js
  src/components/Cards/Cards.js
  src/components/Cards/index.jsx
  src/components/Cards/index.module.css
  src/components/Cardsfolder/index.jsx
  src/components/Cardsfolder/index.module.css
  src/components/Folderdata/Folderdata.js
  src/components/Folderdata/index.jsx
  src/components/Folderdata/index.module.css
  src/components/Foldermenu/index.css
  src/components/Foldermenu/index.jsx
  src/components/Footer/Footer.js
  src/components/Footer/index.jsx
  src/components/Footer/index.module.css
  src/components/Main.jsx
  src/components/Navigation/Nav.js
  src/components/Navigation/index.jsx
  src/components/Navigation/index.module.css
  src/components/SearchBar/SearchBar.js
  src/components/SearchBar/index.jsx
  src/components/SearchBar/index.module.css
  src/homepage.js
  src/index.js
  src/pages/FolderPage.jsx
  src/pages/SharedPage.jsx
  src/utils/hooks/date.js
  src/utils/hooks/useFetch.js
Labels: 순한맛🐑

#322 [김법균] week8
  package-lock.json
  package.json
  src/App.js
  src/assets/css/reset.css
  src/assets/images/add_icon.svg
  src/assets/images/add_icon_white.svg
  src/assets/images/delete_icon.svg
  src/assets/images/kebab.svg
  src/assets/images/link.svg
  src/assets/images/pen_icon.svg
  src/assets/images/purplestar.svg
  src/assets/images/share_icon.svg
  src/assets/images/star.svg
  src/components/Account/Account.js
  src/components/Account/Account.jsx
  src/components/Account/Account.module.css
  src/components/AddLinkBar/AddLinkBar.jsx
  src/components/AddLinkBar/AddLinkBar.module.css
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/FolderInfo/FolderInfo.css
  src/components/FolderInfo/FolderInfo.js
  src/components/FolderInfo/FolderInfo.jsx
  src/components/FolderInfo/FolderInfo.module.css
  src/components/FolderToolBar/FolderToolBar.jsx
  src/components/FolderToolBar/FolderToolBar.module.css
  src/components/FolderToolBar/FolderToolBarButton.jsx
  src/components/FolderToolBar/UtilButton.jsx
  src/components/FolderToolBar/constants.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/Header.jsx
  src/components/LinkCard/LinkCard.css
  src/components/LinkCard/LinkCard.js
  src/components/LinkCard/LinkCard.jsx
  src/components/LinkCard/LinkCard.module.css
  src/components/LinkCardList/LinkCardList.js
  src/components/LinkCardList/LinkCardList.jsx
  src/components/LinkCardList/LinkCardList.module.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/index.js
  src/index.jsx
  src/pages/FolderPage/FolderPage.css
  src/pages/FolderPage/FolderPage.jsx
  src/pages/SharedPage/SharedPage.css
  src/pages/SharedPage/SharedPage.jsx
  src/utils/api.js
  src/utils/convertObjectKeysToCamelCase.js
  src/utils/mockData.js
  src/utils/time-functions/formatDate.js
  src/utils/time-functions/getTimeDifference.js
Labels: 매운맛🔥

#336 [김한샘] week8
  README.md
  package-lock.json
  package.json
  src/App.js
  src/App.jsx
  src/assets/icon/link.png
  src/assets/svg/add.svg
  src/assets/svg/delete.svg
  src/assets/svg/kebab.svg
  src/assets/svg/pen.svg
  src/assets/svg/share.svg
  src/assets/svg/star.svg
  src/components/AddLinkForm/AddLinkForm.css
  src/components/AddLinkForm/AddLinkForm.jsx
  src/components/Card.jsx
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/Card/EditableStarButton.css
  src/components/Card/EditableStarButton.jsx
  src/components/Card/KebobButton.jsx
  src/components/Card/KebobList.css
  src/components/Card/KebobList.jsx
  src/components/CardList.jsx
  src/components/CardList/CardList.css
  src/components/CardList/CardList.jsx
  src/components/CardTitleIcon/CardTitleIcon.css
  src/components/CardTitleIcon/CardTitleIcon.jsx
  src/components/ConHeader/ConHeader.css
  src/components/ConHeader/ConHeader.jsx
  src/components/ContentWrap.css
  src/components/FolderTabList/Button.css
  src/components/FolderTabList/Button.jsx
  src/components/FolderTabList/FolderAddButton.css
  src/components/FolderTabList/FolderAddButton.jsx
  src/components/FolderTabList/FolderTabList.css
  src/components/FolderTabList/FolderTabList.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.jsx
  src/components/Search/Search.css
  src/components/Search/Search.jsx
  src/fetchUtils/index.js
  src/hooks/useToggle.jsx
  src/index.jsx
  src/pages/Folder.jsx
  src/pages/NotFoundPage.jsx
  src/pages/Shared.jsx
  src/routes/index.jsx
  src/utils/GetDate.js
  src/utils/GetDaysAgo.js
Labels: 매운맛🔥

#341 [권주현] Week8
  package-lock.json
  package.json
  src/App.js
  src/assets/card-default.png
  src/assets/error.png
  src/assets/kebab.svg
  src/components/FavoriteLinkCard.js
  src/components/FavoriteLinkCard.module.css
  src/components/FavoriteLinkCards.js
  src/components/GlobalNavigationBar.js
  src/components/UserProfileAndTitle.js
  src/globalComponents/Avatar.jsx
  src/globalComponents/Footer.jsx
  src/globalComponents/Header.jsx
  src/globalComponents/SearchBar.jsx
  src/globalComponents/styles/Avatar.module.css
  src/globalComponents/styles/Footer.module.css
  src/globalComponents/styles/Header.module.css
  src/globalComponents/styles/SearchBar.module.css
  src/index.js
  src/index.jsx
  src/pages/FolderPage/components/AddLinkForm.jsx
  src/pages/FolderPage/components/FolderLinkCard.jsx
  src/pages/FolderPage/components/FolderLinkCards.jsx
  src/pages/FolderPage/components/FoldersController.jsx
  src/pages/FolderPage/components/FoldersList.jsx
  src/pages/FolderPage/index.jsx
  src/pages/FolderPage/styles/AddLinkForm.module.css
  src/pages/FolderPage/styles/FoldersController.module.css
  src/pages/FolderPage/styles/FoldersList.module.css
  src/pages/LinkCard.module.css
  src/pages/LinkCards.module.css
  src/pages/SharedPage/components/SharedLinkCard.jsx
  src/pages/SharedPage/components/SharedLinkCards.jsx
  src/pages/SharedPage/components/UserProfileAndTitle.jsx
  src/pages/SharedPage/index.jsx
  src/pages/SharedPage/styles/UserProfileAndTitle.module.css
  src/services/api.js
  src/services/useAsync.js
Labels: 매운맛🔥

#344 [Week8] 박상준
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.jsx
  src/api/api.js
  src/api/sectionDescription.js
  src/assets/Group36.svg
  src/assets/Search.svg
  src/assets/add.svg
  src/assets/akar-icons_facebook-fill.png
  src/assets/akar-icons_twitter-fill.png
  src/assets/akar-icons_youtube-fill.png
  src/assets/ant-design_instagram-filled.png
  src/assets/image25.png
  src/assets/img_1.png
  src/assets/img_2.png
  src/assets/img_3.png
  src/assets/img_4.png
  src/assets/kebab.svg
  src/assets/link.svg
  src/assets/logo.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/star.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.styled.js
  src/components/Card/Card.jsx
  src/components/Card/Card.styled.js
  src/components/ContentsContainer.jsx
  src/components/FolderButton/FolderButton.jsx
  src/components/FolderButton/FolderButton.styled.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.styled.js
  src/components/Layout.jsx
  src/components/MainSectionCard/MainSectionCard.jsx
  src/components/MainSectionCard/MainSectionCard.styled.js
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.styled.js
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.styled.js
  src/contexts/UserContext.js
  src/index.js
  src/instance/axiosInstance.js
  src/pages/Folder/Folder.jsx
  src/pages/Folder/Folder.styled.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.styled.js
  src/pages/Shared/Shared.jsx
  src/pages/Shared/Shared.styled..js
  src/utils/color.css
  src/utils/font.css
  src/utils/util.js
Labels: 매운맛🔥

#326 Part2 장성훈 week8
  package-lock.json
  package.json
  src/apis/getFolder.js
  src/assets/icon/facebook.svg
  src/assets/icon/instagram.svg
  src/assets/icon/search.svg
  src/assets/icon/twitter.svg
  src/assets/icon/youtube.svg
  src/assets/linkbrary.svg
  src/commonStyles/global.js
  src/commonStyles/reset.js
  src/components/AddLinkInput.jsx
  src/components/App.css
  src/components/App.js
  src/components/Card.jsx
  src/components/FilteringButton.jsx
  src/components/FolderInfo.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Input.jsx
  src/contants/constant.js
  src/hooks/useFetchData.js
  src/index.js
  src/pages/app/App.jsx
  src/pages/folder/Folder.jsx
  src/pages/shared/Shared.jsx
  src/utils/dateLog.js
  src/utils/formatStyle.js
Labels: 미완성🫠

#318 [황은지] week8
  part2/package-lock.json
  part2/package.json
  part2/src/api.js
  part2/src/assets/kebab.svg
  part2/src/assets/link.svg
  part2/src/assets/pen.svg
  part2/src/assets/plus-white.svg
  part2/src/assets/plus.svg
  part2/src/assets/share.svg
  part2/src/assets/star.svg
  part2/src/assets/trash.svg
  part2/src/components/AddLink.js
  part2/src/components/App.js
  part2/src/components/Button/FolderListButton.js
  part2/src/components/Button/GradientButton.js
  part2/src/components/Button/SnsButton.js
  part2/src/components/CardList.js
  part2/src/components/CardList/CardList.css
  part2/src/components/CardList/CardList.js
  part2/src/components/Folder/Folder.css
  part2/src/components/Folder/Folder.js
  part2/src/components/FolderToolBar.js
  part2/src/components/Footer/Footer.css
  part2/src/components/Footer/Footer.js
  part2/src/components/MainContent.css
  part2/src/components/MainContent.js
  part2/src/components/Nav.css
  part2/src/components/Nav.js
  part2/src/components/Nav/Nav.css
  part2/src/components/Nav/Nav.js
  part2/src/components/NoLink.js
  part2/src/components/Profile/Profile.css
  part2/src/components/Profile/Profile.js
  part2/src/components/Search.js
  part2/src/components/Search/Search.css
  part2/src/components/Search/Search.js
  part2/src/pages/FolderPage.js
  part2/src/pages/SharedPage.js
Labels: 순한맛🐑

#346 [박준영] Week8
  package-lock.json
  package.json
  src/App.js
  src/api/api.js
  src/api/attemptSignup.js
  src/api/cardData.js
  src/api/emailduplication.js
  src/api/login.js
  src/api/profile.js
  src/assets/delete.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/plusIcon.svg
  src/assets/share.svg
  src/components/Card.js
  src/components/Cta.js
  src/components/EyesOff.js
  src/components/EyesOn.js
  src/components/Gnb.js
  src/components/Logo.js
  src/components/Star.js
  src/components/addLink.js
  src/components/eyes.js
  src/components/fab.js
  src/components/footer.js
  src/components/menu.js
  src/components/searchBar.js
  src/constants/path.js
  src/pages/Landing.js
  src/pages/SignIn.js
  src/pages/Signup.js
  src/pages/folder.js
  src/pages/shared.js
  src/styles/Landing.css
  src/styles/card.css
  src/styles/color.css
  src/styles/footer.css
  src/styles/gnb.css
  src/styles/searchBar.css
  src/styles/shard.css
  src/styles/signup.css
  src/utils/common.js
Labels: 매운맛🔥, 미완성🫠

#342 [김민섭] Week8
  package.json
  public/index.css
  public/index.html
  src/App.js
  src/api.js
  src/assets/PlusIcon.svg
  src/assets/deleteIcon.svg
  src/assets/editIcon.svg
  src/assets/facebookIcon.svg
  src/assets/instagramIcon.svg
  src/assets/linkIcon.svg
  src/assets/logo.svg
  src/assets/searchIcon.svg
  src/assets/shareIcon.svg
  src/assets/twitterIcon.svg
  src/assets/youtubeIcon.svg
  src/components/AddLinkBar.jsx
  src/components/CategoryBtnList.jsx
  src/components/FolderEditBtns.jsx
  src/components/Footer.jsx
  src/components/GlobalNavbar.jsx
  src/components/Header.jsx
  src/components/LinkList.jsx
  src/components/SearchBar.jsx
  src/hooks/useChangeFolderColor.jsx
  src/hooks/useFormattingDate.jsx
  src/hooks/useGetFolder.jsx
  src/hooks/useGetFolderList.jsx
  src/hooks/useGetLinks.jsx
  src/hooks/useGetProfile.jsx
  src/hooks/useGetTimeAgo.jsx
  src/index.js
  src/pages/SharedPage.jsx
  src/style/theme.js
Labels: 순한맛🐑

#348 [정성혜] week8
  .gitignore
  README.md
  package-lock.json
  package.json
  src/App.js
  src/assets/svg/kebab.svg
  src/assets/svg/link.svg
  src/assets/svg/pen.svg
  src/assets/svg/plus-white.svg
  src/assets/svg/plus.svg
  src/assets/svg/share.svg
  src/assets/svg/star.svg
  src/assets/svg/trashcan.svg
  src/components/AddLink.js
  src/components/Buttons/FolderButton.js
  src/components/Buttons/GradientButton.js
  src/components/Buttons/Snsbutton.js
  src/components/CardList.css
  src/components/CardList.js
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/ContentWrap.css
  src/components/ContentWrap.js
  src/components/Folder/Folder.js
  src/components/Folder/FolderToolBar.js
  src/components/Footer.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Navigator/Navigator.css
  src/components/Navigator/Navigator.js
  src/components/SearchInput/SearchInput.css
  src/components/SearchInput/SearchInput.js
  src/global.css
  src/pages/FolderPage.js
  src/pages/SharedPage.js
  src/styles/form.css
  src/utils/api.js
  yarn.lock
Labels: 미완성🫠

#323 [유호민] Week8
  src/App.js
  src/Components/CardList.js
  src/Components/Folder.js
  src/Components/FolderList.js
  src/Components/Footer.js
  src/Components/LinkCard.js
  src/Components/Loading.js
  src/Components/Login.js
  src/Components/Navbar.js
  src/Components/Profile.js
  src/Components/SearchBar.js
  src/Components/Shared.js
  src/api.js
  src/css/CardList.css
  src/css/Folder.css
  src/css/FolderList.css
  src/css/Profile.css
  src/css/SearchBar.css
  src/css/Shared.css
  src/img/delete.svg
  src/img/kebab.svg
  src/img/no-img.svg
  src/img/pen.svg
  src/img/share.svg
  src/img/star.svg
Labels: 순한맛🐑

#353 [정지성] Week11
  src/assets/Chat.svg
  src/assets/More.svg
  src/assets/Telegram.svg
  src/assets/_close.svg
  src/assets/check.svg
  src/components/Addlink/index.jsx
  src/components/Addlink/index.module.css
  src/components/Cardsfolder/index.jsx
  src/components/Cardsfolder/index.module.css
  src/components/Foldermenu/index.jsx
  src/components/Footer/index.jsx
  src/components/SearchBar/index.module.css
  src/modal/ModalAddToFolder.jsx
  src/modal/ModalDelete.jsx
  src/modal/ModalFolder.jsx
  src/modal/ModalShare.jsx
  src/modal/modalAddToFolder.module.css
  src/modal/modalDelete.module.css
  src/modal/modalFolder.module.css
  src/modal/modalShare.css
  src/pages/FolderPage.jsx
Labels: 매운맛🔥

#351 [week 11] 이현승
  package-lock.json
  package.json
  public/index.html
  src/Hooks/useData.js
  src/Portal/Portal.js
  src/asset/Facebook.svg
  src/asset/Kakao.svg
  src/asset/check.png
  src/asset/close.png
  src/components/AddLink.js
  src/components/Api/Api.js
  src/components/App.js
  src/components/Card.js
  src/components/CardList.js
  src/components/FolderPage/Folder.js
  src/components/FolderPage/FolderBar.js
  src/components/FolderPage/FolderContents.js
  src/components/FolderPage/FolderNameBar.js
  src/components/GlobalStyle.js
  src/components/Header.js
  src/components/Modal/BlueButton.js
  src/components/Modal/DeleteButton.js
  src/components/Modal/ModalAddFolder.js
  src/components/Modal/ModalAddLink.js
  src/components/Modal/ModalDeleteFolder.js
  src/components/Modal/ModalDeleteLink.js
  src/components/Modal/ModalEdit.js
  src/components/Modal/ModalFrame.js
  src/components/Modal/ModalInput.js
  src/components/Modal/ModalShare.js
  src/components/SearchBar.js
  src/components/snsShares/FaceBookShare.js
  src/components/snsShares/KakaoShare.js
  src/components/snsShares/copyUrl.js
  src/pages/FolderPage.js
  src/pages/SharedPage.js
Labels: 순한맛🐑

#356 [조혜진] Week11
  package-lock.json
  package.json
  public/_redirects
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/Components/Article/Article.jsx
  src/Components/Article/Article.module.css
  src/Components/Cards/Cards.jsx
  src/Components/Cards/Cards.module.css
  src/Components/FolderMain/FolderMain.jsx
  src/Components/FolderMain/FolderMain.module.css
  src/Components/Header/Header.jsx
  src/Components/Modal/Modal.jsx
  src/Components/Modal/Modal.module.css
  src/api/parseData.jsx
  src/assets/close.png
  src/assets/close.svg
  src/assets/facebook.png
  src/assets/kakaotalk.png
  src/assets/link.png
  src/constants/baseURL.jsx
  src/global.css
Labels: 매운맛🔥

#359 [김법균] week11
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  src/assets/images/check.svg
  src/assets/images/close.png
  src/assets/images/facebook.svg
  src/assets/images/kakao.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/FolderToolBar/FolderToolBar.jsx
  src/components/FolderToolBar/constants.js
  src/components/LinkCard/LinkCard.jsx
  src/components/LinkCardList/LinkCardList.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.css
  src/components/ModalContents/AddToFolderModal.jsx
  src/components/ModalContents/DeleteModal.jsx
  src/components/ModalContents/FolderInputModal.jsx
  src/components/ModalContents/ModalContents.module.css
  src/components/ModalContents/ShareModal.jsx
  src/index.jsx
  src/pages/FolderPage/FolderPage.css
  src/pages/FolderPage/FolderPage.jsx
  src/utils/shareFunctions/facebooShare.js
  src/utils/shareFunctions/kakaoshare.js
Labels: 매운맛🔥

#360 [김한샘] week11
  package-lock.json
  package.json
  src/assets/icon/close.png
  src/assets/icon/share-facebook-ico.png
  src/assets/icon/share-kakao-ico.png
  src/assets/icon/share-link-ico.png
  src/assets/icon/svg/add-button-img.svg
  src/assets/icon/svg/folder-check.svg
  src/components/AddLinkForm/AddLinkForm.jsx
  src/components/Card/Card.jsx
  src/components/Card/KebabButton.jsx
  src/components/Card/KebabList.css
  src/components/Card/KebabList.jsx
  src/components/Card/KebobButton.jsx
  src/components/Card/KebobList.css
  src/components/Card/KebobList.jsx
  src/components/CardList/CardList.jsx
  src/components/CardTitleIcon/CardTitleIcon.jsx
  src/components/FolderTabList/FolderAddButton.jsx
  src/components/FolderTabList/FolderTabList.jsx
  src/components/Modal/FolderAddModal/FolderAddButton.jsx
  src/components/Modal/FolderAddModal/FolderAddModal.jsx
  src/components/Modal/Modal.css
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalContext.jsx
  src/components/Modal/ShareModal.jsx
  src/fetchUtils/index.js
  src/hooks/useModal.jsx
  src/pages/Folder.jsx
  src/styles/reset.css
Labels: 미완성🫠
